yesodweb/persistent

- persistent-mysql/Database/Persist/MySQL.hs
responsability => responsibility
> Fix typo in MySQL.hs

- persistent-mongoDB/Database/Persist/MongoDB.hs
> Fix typo in MongoDB.hs

- persistent-test/PersistentTest.hs
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- Like insert, but returns a complete Entity
- Resolves #376
> Add insertEntity

- persistent-template/Database/Persist/TH.hs
- persistent-test/CompositeTest.hs
- persistent-test/Init.hs
- persistent-test/PersistUniqueTest.hs
- persistent-test/persistent-test.cabal
- persistent-test/test/main.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Util.hs
1st commit is a somewhat unrelated cleanup for the generic use case (with a primary key). The 2nd commit fixes issue #342 for SQL.
> Get unique primary

- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
> use modifyFailure for better error messages

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-template/Database/Persist/TH.hs
- persistent-test/PersistUniqueTest.hs
- persistent-test/PrimaryTest.hs
- persistent-test/RenameTest.hs
- persistent-test/persistent-test.cabal
- persistent-test/test/main.hs
- persistent/Database/Persist/Sql/Util.hs
> foreign key reference to a primary key

- persistent-postgresql/Database/Persist/Postgresql.hs
I am sorry for the time I took to submit this as a PR.
The change is quite simple, really
Thanks
> Addresses  Postgresql exceptions #353 

- persistent-template/Database/Persist/TH.hs
- persistent/Database/Persist/Quasi.hs
> use Int64 for foreign keys

- persistent/Database/Persist/Class/PersistEntity.hs
Here it is
https://github.com/yesodweb/persistent/issues/413
> Add a Typeable instance for PersistEntity

- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistEntity.hs
https://github.com/yesodweb/persistent/issues/422
> Add functions to get PersistEntity instances from JSON instances

- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Sql/Raw.hs
> Remove unused TemplateHaskell pragmas in persistent.

- persistent-postgresql/Database/Persist/Postgresql.hs
For #274. 
I have created a `mockMigration` function which achieves the desired functionality for Postgresql.
> Postgresql mock migrate

- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
> destroy pool at the end of withPool

- persistent-mysql/Database/Persist/MySQL.hs
> mockMigrate for MySQL Backend

- persistent-mysql/persistent-mysql.cabal
> Mark only InnoDB as officially supported.

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-test/CustomPrimaryKeyReferenceTest.hs
- persistent-test/persistent-test.cabal
- persistent-test/test/main.hs
> Fix adding a foreign key reference to a custom primary key for MySQL

- persistent-sqlite/Database/Persist/Sqlite.hs
> mockMigration for Sqlite backend

- persistent-test/CompositeTest.hs
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/Database/Persist/Types/Base.hs
> fix insertKey with a composite key

- persistent/Database/Persist/Sql/Run.hs
For it's use case and motivation see #503.
> Add liftSqlPersistMPool function

- persistent/Database/Persist/Class/PersistStore.hs
Hi everyone. Just a typo I saw while reading the docs.
peace!
> Just fixes a typo: s/foerign/foreign

- persistent-test/persistent-test.cabal
See this build error: https://travis-ci.org/yesodweb/persistent/jobs/102784846
> Add aeson-compat

- persistent-mongoDB/Database/Persist/MongoDB.hs
Here is an attempt to apply projections to all of the queries in the mongoDB backend, so that only the fields defined on the `PersistentEntity` are fetched from the database.
I'm pretty new to persistent so please review carefully :)
Specifically:
* Behaviour of `repsert`, `replace`, `update`, `upsert`. I'm assuming that currently, if there are extra fields in the database document that persistent doesn't know about, those fields will be lost after the document is replaced.  Therefore, adding projections to the queries doesn't change anything.
* Behaviour of `update`, `updateGet`, `updateWhere`. These functions all use the `updatesToDoc` function which makes the changes using `$set`, etc and so adding projections won't result in data loss.
* There is a TODO …
> Add projections to all mongoDB queries

- persistent-template/Database/Persist/TH.hs
Ghc 8.0 introduces some TH changes that are detailed here:
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0
Adapting to these changes while still maintaining compatibility with
ghc-7.10 required some new CPP hackery, but it now compiles and passes
all tests with both ghc-7.10 and ghc-8.0.
> persistent-template: Make it work with ghc-8.0

- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Class/PersistUnique.hs
Should fix the travis errors in https://github.com/yesodweb/persistent/pull/552.
> Persist record backend

- persistent-template/Database/Persist/TH.hs
Now builds with release candidate 4 of the 8.0.1 release.
> persistent-template: Fix for a *very* late change in ghc-8.0 TH api

- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
sorry for the whitespace deletion setting in my editor
> provide a better error message for an empty list

- persistent-test/src/CompositeTest.hs
- persistent/Database/Persist/Quasi.hs
Add a MySQL fix on top of #590
> Composite primary key with nullable fields

- persistent-test/persistent-test.cabal
- persistent-test/src/CompositeTest.hs
- persistent-test/src/DataTypeTest.hs
- persistent-test/src/Init.hs
- persistent-test/src/MaxLenTest.hs
- persistent-test/src/PersistentTest.hs
- persistent-test/src/UniqueTest.hs
don't log SQL to Travis (it goes over the log limit).
Also do some cleanup of test code
> Travis no log sql

- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
> handle /<- [Nothing] edge case

- persistent-mysql/Database/Persist/MySQL.hs
We need to parse correctly column type information from MySQL
so persistent types will be properly mapped to the ones
persistent-mysql creates in MySQL
Closes #629
> Implement proper column type parsing for MySQL

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/cbits/config.c
- persistent-sqlite/persistent-sqlite.cabal
Also updated changelog and made a version bump in .cabal file.
No changes to existing API were made, just added 2 data structures and 2 functions. This stuff served a good job for me debugging application memory usage so it might be useful to others.
> Added functions to monitor and control SQLite memory usage

- persistent/Database/Persist/Sql/Migration.hs
I studied the source code of the Migrations module and wrote up my findings. If these are correct and welcome, then please accept this token of documentation. Otherwise, I'm happy to edit/update/clarify. Thanks!
> Doc comments to the Migration module

- persistent-template/Database/Persist/TH.hs
Replaces #648 with latest build plan from master.
> Ocharles master

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-sqlite/test/Spec.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/Init.hs
- persistent-test/test/main.hs
- stack-docker.yaml
- stack.yaml
This is the PR from #646 re-raised.
CC: @snoyberg
> Enable foreign key constraints by default for Sqlite backend

- persistent-mongoDB/ChangeLog.md
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/persistent.cabal
Update CHANGELOG, version bump and related haddock documentation
> Persistent 2.7.0 related changes

- .travis.yml
Also validates that the atomic upsert feature works fine.
> Travis CI: Update postgres from 9.4 to 9.6

- .travis.yml
> Switch Travis to use VM environments to solve random test timeouts

- docs/Persistent-entity-syntax.md
> Document precision of time in MySQL

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
This PR implements #730 but adds a changelog entry and bumps the cabal file
> Provide errmsg when step errors

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
* Fixes an accidentally introduced breaking change
* Closes #749 
cc @paul-rouse Can you review?
> Adds `stepConn`, and restores the `step` function

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/MigrationColumnLengthTest.hs
- persistent-test/test/main.hs
This is #686 with a test added to confirm it works (I also tested against a real Yesod project). 
This closes #686
Btw: Thanks @JaSpa! Sorry your PR never got looked at before.
> [persistent-postgresql] Recognize column-widths

- docs/Persistent-entity-syntax.md
> Fixed link to primary and foreign keys section

- development.md
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/cbits/sqlite3.h
- persistent-sqlite/persistent-sqlite.cabal
> Sqlite upgrade to 3.22.0

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/persistent-sqlite.cabal
> Sqlite enable common extensions

- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Sql/Class.hs
Documentation (with expanded examples)
> Document PersistField and PersistFieldSql

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql/JSON.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/CompositeTest.hs
- persistent-test/src/CustomPersistField.hs
- persistent-test/src/CustomPersistFieldTest.hs
- persistent-test/src/CustomPrimaryKeyReferenceTest.hs
- persistent-test/src/DataTypeTest.hs
- persistent-test/src/EmbedTest.hs
- persistent-test/src/EmptyEntityTest.hs
- persistent-test/src/EntityEmbedTest.hs
- persistent-test/src/EquivalentTypeTest.hs
- persistent-test/src/JSONTest.hs
- persistent-test/src/LargeNumberTest.hs
- persistent-test/src/MigrationColumnLengthTest.hs
- persistent-test/src/MigrationIdempotencyTest.hs
- persistent-test/src/MigrationOnlyTest.hs
- persistent-test/src/MigrationTest.hs
- persistent-test/src/PersistUniqueTest.hs
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PrimaryTest.hs
- persistent-test/src/Recursive.hs
- persistent-test/src/RenameTest.hs
- persistent-test/src/SumTypeTest.hs
- persistent-test/src/UniqueTest.hs
- persistent-test/test/main.hs
- persistent/Database/Persist/Class/PersistField.hs
Added `PersistField` and `PersistFieldSql` instances for `Data.Aeson.Value` and new `Filter` operators `(@>.)` and `(<@.)` that work with `Value`.
> JSON addition to Database.Persist.Postgresql

- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Class/PersistUnique.hs
> Add example usages to upsert, upsertBy, repsert

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
> Showable Unique

- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
- persistent/Database/Persist/Sql/Run.hs
> Add example documentaion for some functions

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/cbits/sqlite3.h
- persistent-sqlite/persistent-sqlite.cabal
https://blade.tencent.com/magellan/index_en.html
> Bump sqlite to address RCE bug: megellan.

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- stack.yaml
> Add extended result code functions

- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/persistent.cabal
>  Fix #847: Use simple insert when there are no unique constraints.

- persistent-template/Database/Persist/TH.hs
Closes #850
(I didn't bump the version number since this is just a documentation PR)
> Recommend .persistentmodels as the file extension

- docs/Persistent-entity-syntax.md
This PR adds some docs for the sum type entity feature.
> Sum type docs

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Migration.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/persistent.cabal
> Migration docs

- persistent-template/persistent-template.cabal
- persistent-template/test/TemplateTestImports.hs
- persistent-template/test/main.hs
This implements a test case for #816 . The test currently passes, so the issue appears to be resolved.
> Implement test for #816

- .travis.yml
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-redis/Database/Persist/Redis/Config.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTest.hs
- persistent-test/src/RenameTest.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- stack_lts-10.yaml
- travis/run.sh
> [CI] Add newer resolvers, update tested ones

- persistent-qq/ChangeLog.md
- persistent-qq/package.yaml
- persistent-qq/src/Database/Persist/Sql/Raw/QQ.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTest.hs
- [kinda] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock
> Add support for list of values in sqlQQ

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-sqlite/test/sanity.hs
See changelog for more information
> Retry on busy error from SQLite

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Types.hs
> Remove deprecations

- persistent-test/persistent-test.cabal
> bump persistent-test version

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/test/main.hs
PR for issue #669, using the patch from the issue which seems to be working fine on my systems.
> Support for composite primary key migration in SQLite. Fixes #669.

- persistent-sqlite/ChangeLog.md
- persistent-test/src/PersistentTest.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
tagging @kderme who originally wrote this up, a continuation of #915
> fix qmarks

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
Kudos to @kderme for this! Getting this to run CI again so I can get it released soon.
> Fix Unique Constraints in SQlite

- persistent-template/Database/Persist/TH.hs
A refactor ticket to DRY up some of EntityMap creation code in `Persist/TH`
> Extract functions for creating EntityMaps in Persist/TH

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
> use portID from mongoDB instead of network

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent/Database/Persist/Sql.hs
I didn't update the version or ChangeLog because this is a comments-only change.
> Add comments discouraging incorrect usage

- .travis.yml
- stack.yaml
> .travis.yml: bump GHC 8.6.4 to GHC 8.6.5

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Class.hs
Adds extra RawSql instances discussed in #835
> RawSql instances for 9, 10, 11 and 12-column results

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
> Log exceptions when closing a connection fails

- persistent-mongoDB/persistent-mongoDB.cabal
Corresponding Hackage revision will be going out soon.
This should fix the CI build.
> Add upper bound for MongoDB

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
> Add pool creation functions for `RawSqlite`.

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-template/test/main.hs
> Fix persistent template tests

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/persistent-sqlite.cabal
Fun times! If you need to include the headers in packages depending on persistent-sqlite, it works if you depend on the git commit, but not if you depend on the released package!
> Update cabal data to properly expose SQLite header.

- docs/Persistent-entity-syntax.md
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/persistent.cabal
- persistent/test/main.hs
> Documentation Comments in Quasiquoter

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTestModels.hs
- persistent-test/src/PersistentTestModelsImports.hs
> Don't require importing names with TemplateHaskell code

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
> Require language extensions in a more user-friendly manner

- persistent-template/Database/Persist/TH.hs
- persistent-test/src/PrimaryTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Quasi.hs
> Primary key from record

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Types.hs
> Remove the Natural instances

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/PgIntervalTest.hs
- persistent-postgresql/test/main.hs
For issue #638 
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>
> persistent-postgresql: Implement Postgres interval support

- persistent-template/ChangeLog.md
- persistent-template/persistent-template.cabal
Builds fine and all tests pass here.
> Allow aeson 1.5

- persistent-qq/persistent-qq.cabal
- persistent-qq/src/Database/Persist/Sql/Raw/QQ.hs
- persistent-qq/test/Spec.hs
This are all the commits from #1111 that don't change any behavior; as a separate PR.  I assume these require less discussion + they are useful on their own.  So let's get these merged first!
> persistent-qq: Fix Haddock markup + fix warnings + refactor

- persistent-qq/test/PersistentTestModels.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
> Remove Monad requirement from proxy type

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/test/main.hs
> A fix for #1117, I think

- persistent-test/persistent-test.cabal
Should resolve [this issue](https://github.com/yesodweb/persistent/issues/1116)
> Adds changelog as extra source file

- persistent-mongoDB/persistent-mongoDB.cabal
**Status**: this compiles, currently testing it
> bump bson and mongoDB upper bounds

- .github/workflows/haskell.yml
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/persistent.cabal
- persistent/test/main.hs
This is a backport of #1135 . Thanks to @NorfairKing for the assist!
> backporting #1135

- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent-mongoDB/test/EntityEmbedTestMongo.hs
- persistent-mongoDB/test/main.hs
- persistent-mysql/test/CustomConstraintTest.hs
- persistent-mysql/test/InsertDuplicateUpdate.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/ArrayAggTest.hs
- persistent-postgresql/test/CustomConstraintTest.hs
- persistent-postgresql/test/EquivalentTypeTestPostgres.hs
- persistent-postgresql/test/JSONTest.hs
- persistent-postgresql/test/PgIntervalTest.hs
- persistent-postgresql/test/main.hs
- persistent-qq/test/PersistentTestModels.hs
- persistent-redis/tests/basic-test.hs
- persistent-sqlite/test/main.hs
- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-template/test/OverloadedLabelTest.hs
- persistent-template/test/SharedPrimaryKeyTest.hs
- persistent-template/test/SharedPrimaryKeyTestImported.hs
- persistent-template/test/TemplateTestImports.hs
- persistent-template/test/main.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/HtmlTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistEntity.hs
> OverloadedLabels Support

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/test/main.hs
- persistent-template/Database/Persist/TH.hs
- persistent-template/test/main.hs
- persistent-test/src/GeneratedColumnTestSQL.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Sql/Internal.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/test/main.hs
> support sqlite generated columns

- .github/workflows/haskell.yml
> Update GitHub Actions

- persistent-qq/ChangeLog.md
- persistent-qq/persistent-qq.cabal
> Release fixed test-suite for persistent-qq

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
- stack.yaml
> Use resourcet-pool

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-sqlite/test/main.hs
> Migration fix for #1184

- persistent-mysql/persistent-mysql.cabal
> Increase upper bound on `mysql`

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/OverloadedLabelSpec.hs
> Generate #id labels

- persistent/ChangeLog.md
Just something I noticed when reading through the changelog for this latest release, the diff codeblock for one of the bulletpoints isn't rendering properly, so this is just a PR to correct that :+1:
> Fix diff rendering issue in changelog

- .github/workflows/haskell.yml
> fail on focus

- .github/workflows/haskell.yml
- cabal.project
- persistent-qq/ChangeLog.md
- persistent-qq/persistent-qq.cabal
- persistent-qq/test/PersistentTestModels.hs
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistConfig.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Run.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/Database/Persist/SqlBackend/Internal/IsolationLevel.hs
- persistent/Database/Persist/TH.hs
- persistent/bench/Main.hs
- persistent/bench/Models.hs
- persistent/persistent.cabal
> Support GHC 9

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
> Fix SafeToRemove

- persistent-qq/ChangeLog.md
- persistent-qq/persistent-qq.cabal
- persistent-qq/test/PersistentTestModels.hs
- persistent/ChangeLog.md
> persistent-qq test suite

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/MigrationReferenceSpec.hs
- persistent-postgresql/test/main.hs
> Fix postgres add reference

- persistent-mongoDB/test/main.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/main.hs
- persistent-sqlite/test/main.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/MaybeFieldDefsTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/FieldDef.hs
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Internal.hs
- persistent/Database/Persist/TH.hs
- persistent/Database/Persist/Types.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/MaybeFieldDefsSpec.hs
- persistent/test/Database/Persist/THSpec.hs
Continuation of #1264 
Closes #277
> Support declaring Maybe before the type (continuation)

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
> persistent-mysql: Prevent fetching constraint info from other databases

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
Based on the discussion in #1298.
> Add `RawPostgresql` based on `RawSqlite`

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
Picks up on #1283, resolves conflicts
> Continuation of #1283

- .github/workflows/haskell.yml
- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent-mongoDB/test/EntityEmbedTestMongo.hs
- persistent-mongoDB/test/main.hs
- persistent-mysql/ChangeLog.md
- persistent-mysql/persistent-mysql.cabal
- persistent-mysql/test/main.hs
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/main.hs
- persistent-redis/ChangeLog.md
- persistent-redis/persistent-redis.cabal
- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/DataTypeTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
> Matt/ghc 9.2

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
yesodweb/persistent issue #1361
> Define withPostgresqlPoolModifiedWithVersion

- persistent-qq/test/PersistentTestModels.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/TH.hs
- persistent/test/Database/Persist/ClassSpec.hs
- persistent/test/Database/Persist/THSpec.hs
> Add `tabulateEntityA` to `PersistEntity` class

- persistent/Database/Persist/Class/PersistUnique.hs
> Fix typo upadtes -> updates in PersistUnique

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
Fixes https://github.com/yesodweb/persistent/issues/1410
> Update reference to rawSql

- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/persistent.cabal
> re-export `SafeToInsert` from the main modules

- .github/workflows/haskell.yml
> Don't use Mongo 6 in CI

- flake.lock
- flake.nix
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/persistent.cabal
> Quasi typo fix + nixify

- cabal.project
- persistent-mongoDB/persistent-mongoDB.cabal
> Relax upper bound on http-api-data

- persistent-qq/ChangeLog.md
- persistent-qq/persistent-qq.cabal
- persistent-qq/src/Database/Persist/Sql/Raw/QQ.hs
- persistent-qq/test/CodeGenTest.hs
> Fix comments in persist-qq

- .github/workflows/haskell.yml
- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/THSpec.hs
> Fix warns, fix safetoinsert for only changing name

- persistent/persistent.cabal
> fix conduit lower bound

- persistent-mongoDB/persistent-mongoDB.cabal
- persistent/Database/Persist/TH.hs
- stack.yaml
> Update Stackage resolver

- persistent-mongoDB/persistent-mongoDB.cabal
> Relax pool bounds

- persistent-mongoDB/persistent-mongoDB.cabal
> Allow http-api-data 0.6

- .github/workflows/haskell.yml
- persistent-redis/persistent-redis.cabal
> Add GHC 96 to CI

- README.md
Address #1479. Feel free to modify in any way.
> Add quickstart example

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/persistent-postgresql.cabal
- stack.yaml
> Bump libpq bounds

- cabal.project
- flake.nix
- **build: add SHA256 checksum of mysql dependency for nix**
- **style: remove unnecessary empty line in flake.nix**
- **build: add `mariadb-connector-c.dev` dependency for MySQL library**
> fix: nix build

- persistent/ChangeLog.md
- persistent/Database/Persist/EntityDef.hs
- persistent/Database/Persist/EntityDef/Internal.hs
- persistent/Database/Persist/Types.hs
- persistent/Database/Persist/Types/Base.hs
> Fix export of keyAndEntityFieldsDatabase

- persistent/Database/Persist/Class/PersistField.hs
> Fix formatting for PersistField

- persistent/Database/Persist/Class/PersistUnique.hs
None of the below checklist seems relevant for this kind of change.
> Fix “deleteBy” documentation example (add parenthesis)
