yesodweb/persistent

- persistent-postgresql/Database/Persist/Postgresql.hs
(This is the same as the typo in MySQL, I just happened to find this one after submitting the MySQL PR and was fixing typos from the Github editing interface)
> Fix typo in Postgresql.hs

- persistent-postgresql/Database/Persist/Postgresql.hs
postgresql 9.4 adds support for the jsonb type (a more efficient representation of json data). These changes seem to suffice to use it with sqltype=jsonb on Text fields.
> add support for jsonb type

- persistent-postgresql/persistent-postgresql.cabal
I noticed the version number was one revision behind: http://hackage.haskell.org/package/persistent-postgresql-2.1.2.2
It might be worth noting that a user was having compile errors with this version earlier in IRC: http://dpaste.com/3RZE40T. I've encouraged them to open an issue.
> Bump persistent-postgresql version to match hackage (2.1.2.2).

- persistent/Database/Persist/Class/PersistEntity.hs
Based on the types, the previous instance declarations were not possible.
> Fix ToJSON/FromJSON instance declarations

- experimental/couchDB/persistent-couchdb.cabal
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/persistent-postgresql.cabal
- persistent-redis/persistent-redis.cabal
- persistent-sqlite/persistent-sqlite.cabal
- persistent-template/persistent-template.cabal
- persistent-test/persistent-test.cabal
- persistent-zookeeper/persistent-zookeeper.cabal
- persistent/persistent.cabal
Based on the discussion in #367 about dropping support for GHC 7.4
> Up dependency on the base package to >= 4.6 (removes GHC 7.4 support)

- persistent-test/persistent-test.cabal
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/persistent.cabal
Moved some functionality regarding composite/custom primary keys to an exposed module (perhaps it should be under an "Internal" folder?) so Esqueleto can reuse it. See https://github.com/prowdsponsor/esqueleto/issues/87
> refactor to expose some utilities for Esqueleto

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
Derives `Show` instances for configuration values. The main advantage is easier debugging + it let's you derive `Show` for records that contain a Conf value, like `AppSettings` in the scaffolding.
(MongoDB already derives `Show` for its configuration record).
> Add `Show` instances for MySQLConf, SqliteConf and PostgresqlConf

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
I'm in the process of implementing a library to create PostgreSQL full text search queries using Esqueleto (https://github.com/albertov/esqueleto-textsearch) and I need to create `PersistField` instance for postgres' `tsvector`, `regconfig` and `tsquery` types. I was tempted to add another set of converters for these types in `builtInExtensionGetters` but since it's not the first time I've done this (see #313) I think a more future-proof solution would be to treat all unknown oids as `PersistDbSpecific` values and let the `PersistField` instances parse them as they see fit.
> Treat unknown extension types as PersistDbSpecific values

- persistent-template/Database/Persist/TH.hs
- persistent-test/EmbedTest.hs
confirming the workaround for #375
led to writing a test case exposing bad behavior of
field (Map Text (Key record))
This should not be marked as an embedding
It is just a normal map
> Fix handling of (Key record) in embedding

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-test/CompositeTest.hs
- persistent-test/PrimaryTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/persistent.cabal
Closes #365.
This PR uses Postgres' `RETURNING` capability to optimize bulk-inserts. Instead of inserting one-at-a-time, the rows can be inserted all at once and have their IDs returned. Based on my comment [here](https://github.com/yesodweb/persistent/issues/365#issuecomment-107081911), I don't think this is possible for SQLite/MySQL in a reliable way.
I believe test coverage is already pretty good on this, because several tests use `insertMany`, get back IDs, and then use those IDs to lookup the inserted rows.
Things I'm unsure about:
* The different `InsertSqlResult` types. Is `ISRManyKeys` supposed to be used when a composite primary key is defined?
* Version bumps. Is this considered a breaking change because it adds a new record field to public API?
> Use Postgres' RETURNING capability to optimize `insertMany`.

- .gitignore
- stack.yaml
With persistent we of course have the issue that someone may not have all the C driver libraries installed (which is why I use the Dockerfile). I only have redis & zookeeper commented out right now because I think their deps don't align with stackage, but we can figure that out later.
> add stack.yaml

- persistent-template/persistent-template.cabal
`cabal test`'d with `aeson-0.9.1`, passed:
```
$ cabal sandbox hc-pkg list | grep aeson
aeson-0.9.0.1
```
```
$ cabal test
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring persistent-template-2.1.3.3...
Preprocessing library persistent-template-2.1.3.3...
Database/Persist/TH.hs:12:14: Warning:
-XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[1 of 1] Compiling Database.Persist.TH ( Database/Persist/TH.hs, dist/build/Database/Persist/TH.o )
Database/Persist/TH.hs:62:1: Warning:
The import of ‘Data.Monoid’ is redundant
except perhaps to import instances from ‘Data.Monoid’
To import instances alone, use: import Data.Monoid() …
```
> Relax aeson upper bound for 0.9.x

- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
Closes #419 
This doesn't implement any checking of SQLite version before using the feature. I'm not sure if compiling Persistent with system SQLite is a common use case, though. Ubuntu LTS 12's default SQLite wouldn't support the multi-row insert, but Ubuntu LTS 14 would. Edit: Do you guys think it's worth implementing that? I imagine you'd pass the version of SQLite you're using as a config option?
Had some issues running the tests locally for this, but the existing test suite on Travis covers `insertMany_` in several spots so I'm not too concerned.
> Have SQLite backend use multi-row inserts for insertMany_

- persistent/Database/Persist/Types/Base.hs
I don't see why these extensions are required in the module. Tested by building them without the extensions in `ghc 7.10.1`.
> Removing unused extensions.

- .travis.yml
GHC 7.10.1 is currently an allowed failure due to some version constraint issues in persistent-zookeeper.
> Support multiple GHC versions in travis config

- persistent-zookeeper/persistent-zookeeper.cabal
Both the build jobs[1][2] are failing because of the package time.
I'm removing the version constraint in time since there is already a
constraint placed on time by the persistent package. And looking on the
code of persistent-zookeeper, I don't see why a minimal version of 1.4
is required.
https://travis-ci.org/yesodweb/persistent/jobs/72733457
https://travis-ci.org/yesodweb/persistent/jobs/72733456
> Remove version constraints.

- persistent/Database/Persist/Class/PersistEntity.hs
Similar to the JSON helper function I created a while back. The haddocks I've added should explain the motivations. I'll copy them here: 
+-- | Convenience function for getting a free 'PersistField' instance
+-- from a type with an 'Enum' instance. The function 'derivePersistField'
+-- from the persistent-template package should generally be preferred.
+-- However, if you want to ensure that an @ORDER BY@ clause that uses 
+-- your field will order rows by the data constructor order, this is 
+-- a better choice.
> Add helper functions for getting a PersistField instance for Enums

- persistent/Database/Persist.hs
Added some examples on how to use `||.` and explained how to create a filter for `(A AND B AND (C OR D))`  using `++`. The comments has `&&.` in case people look for it, they will see this comment.
> Improved documentation for ||.

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-test/CustomPersistField.hs
- persistent-test/CustomPersistFieldTest.hs
- persistent-test/persistent-test.cabal
- persistent-test/test/main.hs
Closes #448 
This PR adds a failing test case demonstrating persistent-mysql writing a `PersistText` but reading a `PersistByteString`. The second commit of the PR uses character set information to distinguish between ~~TEXT and BLOB~~ binary and non-binary strings in MySQL, fixing the failing test.
This PR could break existing code. If code is relying on reading a `PersistByteString` from a MySQL `TEXT` column, that code will break (as it did for `getColumn`).
> Distinguish between binary and non-binary strings in MySQL

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-test/PersistentTest.hs
Trying to fetch an arrays with a `NULL` value would not work.  The problem was that it wasn't obvious how `persistent-postgresql` created `PersistentNull` values, so when the work on arrays got merged 1.5 year ago no one noticed it lacked `NULL` treatment code.
This PR adds a previously-failing test and the fix.
> Fix persistent-postgresql's treatment of NULLs inside arrays

- persistent/Database/Persist/Sql/Migration.hs
It would be nice to see the entire migration when an unsafe statement is found, using `runMigration` and friends.
Before:
```
Database migration: manual intervention required.
The following actions are considered unsafe:
DROP TABLE "player";
```
After:
```
Database migration: manual intervention required.
The unsafe actions are prefixed by '***' below:
CREATE TEMP TABLE "player_backup"("id" INTEGER PRIMARY KEY,"device_idee" BLOB NOT NULL);
INSERT INTO "player_backup"("id") SELECT "id" FROM "player";
*** DROP TABLE "player";
CREATE TABLE "player"("id" INTEGER PRIMARY KEY,"device_idee" BLOB NOT NULL);
INSERT INTO "player" SELECT "id","device_idee" FROM "player_backup";
DROP TABLE "player_backup";
```
> Improve failed migration error message

- persistent-sqlite/persistent-sqlite.cabal
- persistent-sqlite/test/sanity.hs
ghc detects build failure as:
Preprocessing executable 'sanity' for persistent-sqlite-2.2.1...
[1 of 1] Compiling Main             ( test/sanity.hs, dist/build/sanity/sanity-tmp/Main.dyn_o )
test/sanity.hs:8:8:
No instance for (monad-logger-0.3.13.2:Control.Monad.Logger.MonadLogger
IO)
arising from a use of ‘withSqliteConn’
In the expression: withSqliteConn ":memory:"
In the expression: withSqliteConn ":memory:" $ const $ return ()
In an equation for ‘main’:
main = withSqliteConn ":memory:" $ const $ return ()
Reported-by: Nick Bowler
Gentoo-bug: https://bugs.gentoo.org/show_bug.cgi?id=561274
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
> persistent-sqlite.cabal: fix test/sanity.hs test

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-test/RenameTest.hs
["Change table Id field type"](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#change-tablecollection-id-field-name-andor-type-persistent--21) with MYSQL.
Since ```default=``` can not be used yet, need to use ```insertKey```.
> Changing id field type for MYSQL

- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-test/CustomPersistField.hs
- persistent-test/CustomPrimaryKeyReferenceTest.hs
- persistent-test/EmbedTest.hs
- persistent-test/Init.hs
- persistent-test/PersistentTest.hs
- persistent-test/PrimaryTest.hs
- persistent-test/RenameTest.hs
- persistent-test/persistent-test.cabal
- stack.yaml
0.11 introduced an arbitrary break in the API. It may be better just to correct that with the following
```
(.:??) :: FromJSON a => Object -> Text -> Parser (Maybe a)
o .:?? k = fmap join (o .:? k)
```
> use an aeson compatibility layer

- persistent-mysql/Database/Persist/MySQL.hs
haddock does not allow sticking docstrings to
unnamed constructor fields:
Database/Persist/MySQL.hs:419:21: parse error on input ‘DBName’
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
> Database/Persist/MySQL.hs: fix haddock markup

- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-redis/Database/Persist/Redis/Store.hs
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-test/persistent-test.cabal
- persistent-zookeeper/Database/Persist/Zookeeper/Store.hs
- persistent-zookeeper/persistent-zookeeper.cabal
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
- stack.yaml
This adds `ToHttpApiData` and `FromHttpApiData` instances and replaces `PathPieces` instance bodies with `toUrlPiece` and `parseUrlPieceMaybe`.
From user's POV this changes instance for `CheckMark` to encode in lower-case and parse case-insensitively.
> Support http-api-data

- persistent/Database/Persist/Class/PersistField.hs
- persistent/persistent.cabal
Hi,
Can you add these changes to support Oracle when using persistent-odbc?
Thanks,
Grant
> add changes to support int8 int16 int32 int64 types in oracle for odbc

- persistent-postgresql/Database/Persist/Postgresql.hs
The old query doesn't work in the scenario where the table is present
but under the ownership of a different user. This query fixes it.
Also it improves the error message related to issue #390.
Instead of an error message like this:
```
SqlError {sqlState = "42P07", sqlExecStatus = FatalError, sqlErrorMsg =
"relation \"person\" already exists", sqlErrorDetail = "",
sqlErrorHint = ""}
```
You get this:
```
SqlError {sqlState = "42501", sqlExecStatus = FatalError, sqlErrorMsg =
"must be owner of relation person", sqlErrorDetail = "", sqlErrorHint =
""}```
> Change the query for checking existence of Table

- development.md
- persistent/Database/Persist.hs
- persistent/Database/Persist/Class/DeleteCascade.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Class/PersistQuery.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Class/PersistUnique.hs
These include the following changes:
* Minor cosmetics: every line should not exceed 80 column, majority of descriptions start with capital letter and end with a full stop. For consistency all descriptions should be written this way.
* Typo corrections. There are a couple of them.
* Added new doc-strings where they were missing.
* Use proper and consistent Haddock syntax everywhere. In a couple of places it makes code examples readable. See `(||.)` for example.
* Minor refactoring. This is not the main aim of this PR, but I changed a couple of lines when GHC and HLint asked me to do so.
----
This PR is WIP. I need your help. Please propose descriptions for `limitOffsetOrder` and `getPersistMap`. If you think some changes are unnecessary, tell me.
> Documentation improvements

- persistent-sqlite/persistent-sqlite.cabal
- GCC on SmartOS needs explicit -std=c99 to build cbits/sqlite3.c
> Build on SmartOS

- persistent/Database/Persist.hs
Adds documentation to basic query combinators with an example schema along with a sample data. I'm planning to add similar line of examples to other combinators as well. So if there is any concern/request/criticism, I would like to hear it in a very early stage! The major motivation for adding this is after my personal experience with haskell newbies who were finding this difficult to use.
CC: @snoyberg , @gregwebs
> Document combinator (=.) along with examples.

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
This should resolve #535.
I only changed how TINYINT is treated. So if your database structure has a TINYINT of length 2 or 3 it will be treated as a PersistInt64, while TINYINT of length 1 will still be PersistBool. It is worth mentioning that MySQL treats Length as how many digits to display. So a length 1 TINYINT could contain more than 0 and 1. However, distinguishing between a TINYINT that is used a bool or 0-9 is not possible.
> Determine type based on Length and Type from MySQL Schema

- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
Sqlite connection can be set to read-only access now.
The default for sqlite connections remains intact (WAL on and READWRITE)
By adding "READONLY " behind an optional "WAL=off ", it is now possible to forbid write actions to the database. Also, when no db file exists, an error is thrown (in the READWRITE default case: the file is created).
The c function `sqlite3_open` is replaced by `sqlite3_open_v2` which allows to set the appropriate flag for read-only access and behaves like `sqlite3_open` otherwise.
> allow read-only access to sqlite dbs with optional param in connection string

- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Class/PersistUnique.hs
@pseudonom I am trying to combat the increased size of type signatures from the read/write split (not released to hackage yet). Do you think it would be good to use this alias everywhere?
> add a PersistRecordBackend type alias

- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
It seems as if the original fix somehow confused the issue, since the issue was that type_0 is reserved, in 7.10.2, but adding an extra `_` makes it ok (i.e. `type__0`). This pull request applies the previous fix in the correct place, and works in my case. See issue #412 for more details on the bug.
> Fix for issue #412

- persistent-redis/Database/Persist/Redis/Internal.hs
- persistent-redis/Database/Persist/Redis/Store.hs
- persistent-redis/persistent-redis.cabal
- stack-docker.yaml
- stack.yaml
For #567. Persistent-redis supports a type class split in 2.5 version of persistent.
> persistent-redis with version 2.5

- persistent-redis/persistent-redis.cabal
Dependency constraints are lifted for compatibility with GHC 8.0.1.
> Fixed dependencies to satisfy GHC 8.0.1 constraints

- persistent-redis/Database/Persist/Redis/Store.hs
- persistent-redis/persistent-redis.cabal
Fixed test dependency constraints
Added missing instance of HasPersistBackend
Version bump to 2.5.2
For #567
> Redis backend fixes for GHC 8.0.1 and Persistent 2.5

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/Database/Persist/Types/Base.hs
I have created this PR for getting review.
Things that work now:
* Atomic upsert for postgresql work
Things that have to be done:
* Raise exception when there is more than one uniqueness constraint for an `EntityDef`.
* Fix other backend errors - Right now works only for postgresql
Question I have:
In what scenario will the field `uniqueFields` have more than one element in the list. Why it is modelled as a List data strcuture instead of a tuple like `(HaskellName, DBName)` ?
The `UniqueDef` type for reference:
``` haskell
data UniqueDef = UniqueDef
{ uniqueHaskell :: !HaskellName 
, uniqueDBName  :: !DBName
, uniqueFields  :: ![(HaskellName, DBName)] -- why list instead of single tuple ?
, uniqueAttrs   :: ![Attr]
}
deriving (Show, Eq, Read, Ord)
```
> Atomic upsert support for Postgresql

- .travis.yml
Once the CI officially supports 9.5, we can switch to that. Switching to
9.5 will verify us that the atomic upsert feature of postgres works as
expected.
> Travis Postgres server update to 9.4

- persistent/Database/Persist/Sql/Types.hs
Whatever module synonym "R" pointed to is gone, and "withStmt" may be lost to time as well.
> Remove dangling doc reference to R.withStmt

- persistent-test/src/PersistentTest.hs
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
This method is similar to `insertEntity`.
Closes #616.
> Add getEntity helper method.

- persistent-mysql/persistent-mysql.cabal
- persistent-test/persistent-test.cabal
This is best done before we try to get persistent-mysql back into stackage.
The changed types/instances in mysql-simple don't seem to used at all by persistent-mysql, so I believe we only need a minor version bump here (or even a hackage revision) - there are extra tuple instances for QueryResults and an extra field in ResultError.
> Relax upper bound on mysql-simple

- persistent-mysql/persistent-mysql.cabal
- persistent-test/persistent-test.cabal
I'll release mysql-simple-0.4.0.0 soon, but I'll let you do this first to avoid unnecessary bounds issues in the next stackage build.
The theoretically-breaking change is another addition to ResultError, and as before it shouldn't affect persistent-mysql versioning.  I had missed it while working through the old PRs :-(
> Relax upper bound on mysql-simple - again

- persistent-mysql/Database/Persist/MySQL.hs
Current `peristent-mysql` code treats `DEFAULT NULL` in DB as no default value so as a result we get noop migrations setting it to `DEFAULT NULL` for columns with `default=NULL` in entity declaration.
This PR fixes it
> Proper mysql default migrations

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/test/Spec.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/persistent.cabal
This fixes #527.
- I haven't run the test suite against MySQL or PostgreSQL, but they should work.
- I added a dependency on split to avoid having to reimplement `chunksOf`, I can remove this if necessary.
- This change adds a field to the `SQLBackend` type and will require a one-line change to packages implementing SQL backends.
> Fix #527 by implementing chunking in insertMany_

- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
Fixes #650 
`getJustEntity` is similar to `getJust` but returns `Entity` instead of just the record. `insertRecord` inserts the record and returns it.
> Convenience functions: getJustEntity and insertRecord

- .gitattributes
The repo language distribution is heavily skewed towards "C" (86%) due to the presence of  `sqlite3` library within the repo. While there are some additional fixes applied on top the public [v3.12.1 amalgamation](https://github.com/azadkuh/sqlite-amalgamation/tree/3.12.1), it is minor enough we could mark the entire directory as [linguist-vendored](https://github.com/github/linguist#using-gitattributes) so the persistent repo appears as a predominantly haskell repo.
This is what I get after adding the `.gitattributes` file and [running linguist](https://github.com/github/linguist#usage) from the project root.
```
$ linguist 
99.88%  Haskell
0.12%   Shell
```
P.S. Diff between repo sqlite .c and original from sqlite amalgamation:
```diff
$ diff  persistent-sqlite/cbits/sqlite3.c …
```
> Fix language stat(s) for persistent repo.

- persistent-postgresql/Database/Persist/Postgresql.hs
I'm using persistent-postgresql with Amazon Redshift. There's a bug in Redshift that doesn't allow any user to call `show server_version`, so all of my connections fail. I was able to workaround this initially by removing all checks for the server version (my first commit) and now I would like to pass in my own function for providing the version.
> Allow separate version check for PostgreSQL

- persistent/Database/Persist/Class/PersistStore.hs
This was probably a copy & paste error in #620. There's no need to require a `PersistStoreWrite` when only doing a get operation.
> Relax constraint on `getEntity`

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
This PR undoes #641, which broke text/blob fields (#671), and fixes the handling of "default=NULL" by silently ignoring it.  Giving this default explicitly never makes any difference, since it is the implicit default for any nullable field.  The original problem addressed by #641 is that MySQL does not retain the distinction between the implicit and explicit versions, so migration could get confused, but #641 resolved the ambiguity in the direction of the explicit declaration, which causes an error for text/blob fields.  This PR goes in the other direction, and makes it implicit.
@snoyberg This is relatively serious, because the Yesod MySQL scaffolding is currently broken, but perhaps @qrilka would like a little while to confirm that the original problem is fixed.
> Fix #671 - revise handling of 'default null' in mysql

- persistent-mysql/Database/Persist/MySQL.hs
MySQL has a native upsert in `INSERT ... ON DUPLICATE KEY UPDATE ...`. This PR introduces that functionality to `persistent-mysql`.
It also introduces a `bulkInsertOnDuplicateKeyUpdate` function, which has an API I'd like feedback on.
> MySQL on duplicate key update

- persistent-postgresql/Database/Persist/Postgresql.hs
Following on #665, this just adds variants for two more functions that allow the server version check to be customized (avoided, really).
cc @dfithian
> More variants for AWS Redshift compatibility

- persistent-template/Database/Persist/TH.hs
The comment on `mpsGeneric` in `MkPersistSettings` says it defaults to `True`, but [here](https://github.com/tvision-insights/persistent/blob/mps-generic-comment/persistent-template/Database/Persist/TH.hs#L373) we can see that it defaults to `False`.
> Update comment to reflect the state of things

- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
I ran into this exception:
```
PersistMarshalError "Unexpected in selectKeys False: [PersistText \"...\"]"
```
This change fixes the issue.
It is possible this may allow a case that it shouldn't but that will just mean the exception is delayed to a few more lines later.
> allow non-numeric keys for selectKeys

- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
- persistent-template/Database/Persist/TH.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Run.hs
Fixes a few wrong haddock `@since` markups, moves to always use `@since` (vs. mixed Since/`@since`), and cleans up some whitespace issues.
> A few markup improvements

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
Exposed parseReferences so that custom QuasiQuoters could be made. If there is a reason not to do this please reject the PR.
> expose parseReferences for the creation of custom QuasiQuoters

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/DataTypeTest.hs
- persistent-test/src/InsertDuplicateUpdate.hs
- persistent-test/test/main.hs
This PR extends the `insertManyOnDuplicateKeyUpdate` function to allow conditional copying of data from the input record.
Use case: Suppose you're importing a report that sometimes has partial data, and you want to copy the report into the database. The result record may have many `Nothing` fields. If we copy this using the current `SomeField`, then we will overwrite the existing data with `NULL`s. Oops.
The new constructor and functions permit us to avoid copying bad data, including `NULL` and empty strings, into the database, potentially overriding already present data.
> [persistent-mysql] Add support for conditional copying

- persistent-mysql/ChangeLog.md
- persistent-mysql/persistent-mysql.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/DataTypeTest.hs
- persistent-test/src/Init.hs
This handles tests of fractional seconds in date/time types (introduced in MySQL 5.6.4) and a change to a strict SQL mode (introduced as the default in MySQL 5.7.5).  A lower-bound update on `mysql-simple` is needed for the fractional seconds.
> Update tests to allow for MySQL behaviour changes

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-test/src/InsertDuplicateUpdate.hs
The current behavior of `insertManyOnDuplicateKeyUpdate` will perform an `insertMany_` if there are no updates to perform. `insertMany_` will then throw an error if the key already exists in the database.
This is surprising -- typically, when you're doing a bulk upsert like this, the desired behavior is "Try to insert these rows into the database. If there's a key collision, then perform the set of updates." Given an empty set of updates, I would expect nothing to be done to the preexisting record, not throwing an exception and rolling back the entire insert.
MySQL's `INSERT IGNORE` is a little unfortunate: [docs](https://dev.mysql.com/doc/refman/5.5/en/insert.html)
> If you use the IGNORE modifier, errors that occur while executing the INSERT statement are ignored. For example, without …
> [persistent-mysql] Use an "INSERT IGNORE" query if the updates are empty.

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/persistent-sqlite.cabal
There are two reasons for this:
1. The cabal user guide recommends [preferring pkg-config dependencies if available](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-pkgconfig-depends)
2. Building a dependent package against persistent-sqlite that uses system libraries fails to fine `libsqlite3.so.0`. I don't quite understand the internals of why this occurs, but it works when using pkg-config.
I also added an extra flag to switch back to the previous behaviour, though I'm not so sure it's even necessary.
> Link against sqlite using pkgconfig by default.

- persistent-test/src/PersistUniqueTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistUnique.hs
This PR adds a `insertUniqueEntity` helper method.
This is a combination of `insertEntity` and `insertUnique`:
```haskell
insertEntity :: record -> ReaderT backend m (Entity record)
insertUnique :: record -> ReaderT backend m (Maybe (Key record))
insertUniqueEntity :: record -> ReaderT backend m (Maybe (Entity record))
```
> Add insertUniqueEntity method

- persistent-mysql/Database/Persist/MySQL.hs
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
This PR introduces some machinery for generalizing the SQL backend requirement, and uses that to generalize the `insertOnDuplicateKeyUpdate` functions.
This PR enables support for the [`persistent-typed-db`](https://github.com/parsonsmatt/persistent-typed-db) library which wraps the `SqlBackend` with a phantom type to indicate which database models are associated with. This turns mixing up your connection and models in a multi-db environment into a compile time error.
This PR is based on [work done in a PR to `esqueleto`](https://github.com/bitemyapp/esqueleto/pull/53). I was able to get esqueleto queries working by incorporating the `BackendCompatible` class to Esqueleto and instantiating it appropriately in the application.
The `BackendCompatible` class and the `HasPersistBackend` / …
> Introduce `BackendCompatible` class

- persistent-test/persistent-test.cabal
- persistent-test/src/DataTypeTest.hs
This is just a bug fix in the test, and applies only to MySQL.  I'll merge it if/when Travis succeeds.
The bug was manifested in https://travis-ci.org/yesodweb/persistent/jobs/291041880 as
```
src/DataTypeTest.hs:74:
1) data type specs handles all types
expected: ("time",02:12:60)
but got: ("time",02:13:00)
```
and there is a similar, though much rarer, potential problem rounding UTCTime.
> persistent-test: safer MySQL-specific rounding of time in DataTypeTest

- .travis.yml
I noticed that  significant amount of the time on Travis is spent building library dependencies. This line should allow `stack` to cache the `extra-deps` libraries.
> Cache .stack-work in Travis script

- .travis.yml
Reverts yesodweb/persistent#719
This change did give a useful speed up for the lts-2 tests, but actually slowed down the tests for lts-6 and later by one to one-and-a-half minutes each.  The overall gain is therefore quite small, and in any case we will probably stop testing against lts-2 fairly soon.  Therefore it seems best to err on the side of keeping the tests as clean as possible.
> Revert "Cache .stack-work in Travis script"

- .travis.yml
PR #717 adds haskell-src-meta, and the lts-2 tests fail on needing `happy`.  This is just a change of test setup, so I'll merge when travis has finished.
> Fix tests to allow testing #717

- persistent-test/src/CompositeTest.hs
- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Raw/QQ.hs
- persistent/persistent.cabal
I'm having a go at #716, now you can do:
```haskell
let lft = 10 :: Int
rgt = 20 :: Int
width = 50 :: Int
[executeQQ|
DELETE FROM category WHERE lft BETWEEN #{lft} AND #{rgt};
UPDATE category SET rgt = rgt - #{width} WHERE rgt > #{rgt};
UPDATE category SET lft = lft - #{width} WHERE lft > #{rgt};
|]
```
Would be great if you could help me figure out how to pass a function into `makeExpr` so that I don't have to duplicate the whole block of code:
https://github.com/felixSchl/persistent/blob/7856bd3878aadb9a703360d76934a7b7e78c66a4/persistent/Database/Persist/Sql/Raw/QQ.hs#L37-L49
I've also updated the test bed to include a few basic tests for this:
https://github.com/felixSchl/persistent/blob/7856bd3878aadb9a703360d76934a7b7e78c66a4/persistent-test/src/PersistentTest.hs#L891-L913
> Implement rawSql as a QuasiQuoter

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/MigrationTest.hs
Fixes #735 
@MaxGabriel,  @psibi would one of you mind checking my logic, please?  The issue is that migration can involve creating a temporary table, and we were adding foreign key constraints that existed in the table being copied.  Sqlite doesn't handle FK constraints from temporary tables to non-temporary ones - it probably doesn't make sense to do so - and when checking is switched on, it reports them as violated.
The fix is simply to omit the FK constraint from the temporary table!
> Sqlite: do not add foreign key constraints to temporary tables

- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Raw/QQ.hs
My mistake when reviewing #717 - the haddock documentation needs to be moved to the functions to make it visible, since it's in an unexposed module.  This should have been a review action, and only affects documentation comments, so I'll merge it straight away so that I can release 2.6.2.
> Rearrange documentation added in #717

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
This change is in hopes of improving the experience/offering a quicker resolution for users like this one: https://www.reddit.com/r/haskell/comments/7erfio/persistmarshalerror_when_using_text_haskell_value/
These are the docs for PersistDbSpecific, which have a great example of using a custom type: https://www.stackage.org/haddock/lts-9.14/persistent-2.7.1/Database-Persist-Types.html#t:PersistValue
A longer term solution might be #731.
cc @parsonsmatt
> Recommend the PersistDbSpecific docs if someone gets an error about them

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/MigrationIdempotencyTest.hs
- persistent-test/test/main.hs
A fix and a test for MySQL migrations containing certain backend-specific sqltypes (i.e. `mediumtext`, `longtext`, `mediumblob`, `longblob` and custom precision `double`).
Closes #752
> Fix mysql sqltype migrations [#752]

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Migration.hs
- persistent/Database/Persist/Sql/Raw.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/persistent.cabal
This reverts commit 7c005338627372dbad623dedcb80569d6d42675e.
This releases a new version that fixes the breaking changes we accidentally released.
> Revert "More BackendCompatible generalizations (#723)"

- persistent-redis/ChangeLog.md
- persistent-redis/persistent-redis.cabal
`persistent-redis` is out of Stackage. With this PR, I'm planning to bring it back.
@snoyberg Can you upload a new version to Hackage ( or alternatively can you give me Hackage access to that) ?
> Fix persistent-redis for Stackage lts-10

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/EquivalentTypeTest.hs
- persistent-test/test/main.hs
* These types are synonyms, with the exact same memory representation in Postgres
* So there's no need to suggest migrating from one to the other https://stackoverflow.com/a/4849030/1176156
My use case is that I have a database not using Persistent for migrations, and I want to use persistent to interact with it. I would also like to check that Persistent's models match the database schema by running `getMigration` and ensuring there are no changes to be made, but if there are spurious migrations then I'll have false positives.
In this database, `text` is being used instead of `varchar`, so Persistent claims it needs migrations. Since `text` and `varchar` are synonyms, this should be unnecessary.
**Edit:**
I found another, similar issue where Persistent would try to migrate a domained …
> Don't migrate between text and varchar in Postgres / domains

- .gitignore
- persistent-test/src/Init.hs
An alternate implementation would be creating the test directory, but that seemed unnecessary and just more confusing, if there was only one file being put into that directory
Closes https://github.com/yesodweb/persistent/issues/745
> Don't require a `test` directory to exist when running SQLite tests

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/reproductionTemplates/mongo.hs
- .github/reproductionTemplates/mysql.hs
- .github/reproductionTemplates/postgresql.hs
- .github/reproductionTemplates/sqlite.hs
- CONTRIBUTING.md
This PR is the Persistent version of https://github.com/yesodweb/yesod/pull/1451
It makes some small changes for Persistent, but is generally pretty similar.
A major change is that I've created templates for the MySQL, Postgres, SQLite and MongoDB backends to help users create small scripts to reproduce issues.
(As a side note, I think that documentation for getting a minimal running setup for each backend is lacking and these scripts should be adapted into such documentation).
The scripts themselves could especially use reviewing since the contributing guidelines have already been merged into yesod and wai.
Closes #746
> Add Github templates and files to help with reproducing issues

- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
My coworker was using a custom primary key like so:
```
User sql=users
Id sqltype=uuid default=uuid_generate_v4
email Email sqltype=text
UniqueEmail email
createdAt UTCTime
modifiedAt UTCTime
deriving Show Eq Typeable
```
But didn't specify the type of the Id to be UUID. This caused Persistent to expect an Int64, leading to a very confusing error message on insert:
```
*** Exception: runFakeHandler issue: InternalError "Invalid result from a SQL insert, got: [PersistDbSpecific \"70c2418d-fb00-43f7-818d-eaf962612030\"]
```
By providing the actual underlying error, it gets much clearer:
```
*** Exception: runFakeHandler issue: InternalError "Invalid result from a SQL insert, got: [PersistDbSpecific \"70c2418d-fb00-43f7-818d-eaf962612030\"]. Error was: \"int64 Expected Integer, received: …
```
> Improve error message when a SQL insert fails with a custom primary key

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
This is kind of ugly, I'm happy to take feedback.
> Allow Postgres migrations to enable extensions

- persistent/Database/Persist/Class/PersistEntity.hs
This PR removes the `PersistEntity` constraint on the `Entity` data constructor, which allows us to derive `Generic` for the type.
Fixes #694
> Add Generic instance and remove constraint on Entity

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-test/src/InsertDuplicateUpdate.hs
- stack.yaml
I want to get this in before 3.0 :smile: 
`SomeField` worked as a name before the responsibility of the type grew. Renaming it makes it more clear what it does and what it is for. Hiding the constructors allows us to add additional combinators without them being breaking changes -- I want to add `copyUnlessIn`, `modifyUsing` and possibly others at some point.
I'm not 100% on the new type alias and pattern constructor for `SomeField`. They'll prevent it from breaking with a compile error and instead issue a deprecation notice for migration, which is helpful, but also extends the amount of backwards compatibility cruft we have to carry around.
> [persistent-mysql] Rename SomeField type to HandleUpdateCollision

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
Address [persistent#778](https://github.com/yesodweb/persistent/issues/778).
- Linked to Issue instead since it has reference to the why and usage sample for new API
> Fix #778 | persistent-template - Add `persistManyFileWith`

- .gitignore
- docs/Persistent-entity-syntax.md
- persistent-test/persistent-test.cabal
- persistent-test/src/UniqueTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/persistent.cabal
I needed to be able to specify the database name of a unique constraint. This was triggered by the porting of a client's Groundhog schema to Persistent. I didn't want to drop and then create the constraint with `snake_case` syntax and I imagine this has come up at some point for someone else so I'm adding it.
Please let me know if I missed anything.
> Add sql= to unique constraints

- CONTRIBUTING.md
- README.md
- development.md
Documentation changes explaining how to build against a subset of targets if only some of the required backends are installed, fixes #808.
> Document building a subset of targets.

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/cbits/sqlite3.h
- persistent-sqlite/persistent-sqlite.cabal
- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/persistent.cabal
Fix [832](https://github.com/yesodweb/persistent/issues/832): `repsertMany` now matches `mapM_ (uncurry repsert)` and is atomic for supported sql back-ends.
> Fix #832: `repsertMany == mapM_ (uncurry repsert)` and is atomic.

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
Alters the error message that appears when marshalling DB values to include the name of the table. I have found it useful to know the table when this error rears its head with generic field names (`lastAccessed` for example), allowing me to go straight to the offending table.
---
I'm not sure which of these I need to complete for this change (bumping version number seems drastic, and I've not changed any public facing API):
> Improve error message when marshalling fails

- persistent/Database/Persist/Class/PersistField.hs
Very minor improvement, as such there is:
* no versions bump (change can be added with the next release, be it major or minor)
* no need for documentation or changelog update
> Remove redundant `fromIntegral` calls

- persistent-template/bench/Main.hs
- persistent-template/bench/Models.hs
- persistent-template/persistent-template.cabal
I was going to see if optimizing the parser would net meaningful compilation gains, but it doesn't appear to be that slow.
Here's the output from a run on my laptop:
```
benchmarking Parsing/Increasing model count/1x10
time                 902.7 μs   (895.7 μs .. 911.2 μs)
0.999 R²   (0.999 R² .. 1.000 R²)
mean                 906.8 μs   (901.8 μs .. 916.8 μs)
std dev              22.43 μs   (11.78 μs .. 36.48 μs)
variance introduced by outliers: 14% (moderately inflated)
benchmarking Parsing/Increasing model count/10x10
time                 915.1 μs   (910.9 μs .. 919.7 μs)
1.000 R²   (0.999 R² .. 1.000 R²)
mean                 917.2 μs   (913.1 μs .. 925.6 μs)
std dev              19.59 μs   (11.16 μs .. 36.22 μs)
variance introduced by outliers: 11% (moderately inflated)
benchmarking …
```
> Add benchmark for persistent-template

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
This adds a version of `openSimpleConnWithVersion`. Since I never use old versions of PostgreSQL that lack upsert support, I want to be able to avoid doing round trip checks of the version each time I create a connection via `openSimpleConn`.
> Add openSimpleConnWithVersion function to persistent-postgresql

- persistent-mysql/test/main.hs
- persistent-postgresql/test/main.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/test/main.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/Init.hs
- persistent-test/src/PersistentTest.hs
- persistent-test/src/ReadWriteTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
> This PR adds read/write tests to check functionality on the read/write backens.

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
> Fix upsert SQL to take a list of unique defs

- persistent/Database/Persist/Sql/Raw.hs
Easy way to avoid most of the problems associated with #896.
> Recommend `rawExecute` when return value is not expected.

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/persistent-sqlite.cabal
STAT4 expands the ANALYZE command's logic, logging more data when using ANALYZE allowing for better query plan optimisation. This PR enables this code by default and adds flags to toggle which profiling/analysis code to build.
> Enable the SQLITE_ENABLE_STAT4 flag by default.

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/Database/Sqlite/Internal.hs
- persistent-sqlite/persistent-sqlite.cabal
Allows people to use the FFI to call SQLite's C API functions. Fixes #771.
> Expose underlying raw SQLite database pointer.

- persistent-sqlite/Database/Persist/Sqlite.hs
SQlite seems to ignore Unique Keys when there is a Primary Key.
This 
```
share [mkPersist sqlSettings, mkSave "entityDefs"] [persistLowerCase|
Person
name String
creditcard Int
Primary name
UniqueA creditcard
|]
``` 
translates into 
` CREATE TABLE "person"("name" VARCHAR NOT NULL,"creditcard" INTEGER NOT NULL, PRIMARY KEY ("name"))`
while after the fix
` CREATE TABLE "person"("name" VARCHAR NOT NULL,"creditcard" INTEGER NOT NULL, PRIMARY KEY ("name"),CONSTRAINT "unique_a" UNIQUE ("creditcard"))`
> Fix Unique Constraints in SQlite

- persistent-test/src/PersistentTest.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
This pr fixes a small bug, which appears when using the `Filter` data type. The test added fails with
```
src/PersistentTest.hs:87:3: 
1) persistent Filter In
uncaught exception: SqliteException
SQLite3 returned ErrorError while attempting to perform prepare "SELECT \"id\", \"name\", \"age\", \"color\" FROM \"Person\" WHERE (\"name\" IN ?)": near "?": syntax error
```
The issue is that `?` should be wrapped in `( )` or sqlite can't parse it.
There seems to be more issues related to the `Filter` data type. For example someone could write `Filter PersonName (FilterValues ["a", "b"]) Eq` which will also fail. An additional fix could be:
- Hide Filter from users so that it is a Opaque type. Users will have to use the combinators from `Database.Persist`
- make constuctors safer, so that ie …
> Fix qmarks

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
TH code generation makes up a significant amount of compile time (see also
#924) and forcing all entities that reference each other to be in a single TH
block means that ALL the code generation has to be redone and recompiled
whenever a single entity changes.
The reason that persistent requires all entities to be in the same TH block is
to properly setup the cross-references from foreign keys when generating a
Migration.
All the logic to build a Migration from a list of `EntityDef`s is already
exposed in persistent/persistent-template, so it's perfectly possible to
generate the `Migration` at runtime from independent entity definitions. The
only thing stopping users from doing this is that the logic to setup the
cross-references for foreign keys is...complicated.
`parseReferences` …
> [persistent-template] Expose the knot tying logic of `parseReferences` directly

- persistent-sqlite/Database/Persist/Sqlite.hs
This fixes the broken instances in 2.10.2 and 2.10.3, but we should probably add tests to avoid this happening again.
> Replace liftPersist, fixes #933

- docs/Persistent-entity-syntax.md
- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Internal.hs
This change adds support for a `constraint=` attribute that allows users to override the automatically generated foreign reference constraint names with their own. The motivation for this change is that we had two instances of very long table/column names that led to automatically generated constraint names exceeding 64 characters, which [is not allowed in MySQL](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html). Without a change like this we could not use the `printMigrations` output.
Please let myself (@charukiewicz) or @belevy know if you have suggestions for a better solution or alternative approach.
> Add support for constraint= attribute to override foreign reference constraint names

- persistent-template/Database/Persist/TH.hs
Another refactor/tidy up of the `TH.hs` file, makes the formatting/indentation consistent across all the functions, extracts/renames a function used to read a file from the filesystem, and makes some code fixes suggested by `hlint`.
> Tidying up code in Persist/TH.hs

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
This pr adds support for foreign keys, table constraints in SQLite. They can only reference Primary keys of other tables and not Unique keys, since this would require changes in `Quasi` and I'm not sure how well this is supported in other dbs. I've tested migrations from existing schemas, which adds new foreign keys to existing Tables and it also works fine.
> Support Table Foreign Key Constraints in SQLite

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Migration.hs
- persistent/persistent.cabal
This PR addresses: #474, #640, #948, and #966.
This would obsolete PR: #965
> Add Quiet variants of runMigration, functioning as workaround for the broken runMigrationSilent

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
> Update module comment in Database.Persist.TH

- persistent/Database/Persist/Sql/Migration.hs
> Eliminate use of `error` in favour of `throwIO`.

- persistent-mysql/persistent-mysql.cabal
- persistent-mysql/test/CustomConstraintTest.hs
- persistent-mysql/test/main.hs
This PR ports the Postgresql `CustomConstraintTest` from #979 to the MySQL backend. 
> MySQL `constraint=` attribute test

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- stack-nightly.yaml
- stack.yaml
- stack_lts-10.yaml
- stack_lts-12.yaml
This patch removes the overlapping `instance Lift' a => Lift a` by replacing the three `Lift'` instances with `Lift` instances:
* There has been an `instance Lift a => Lift [a]` in `template-haskell` for a while now, so that one is already covered.
* The `instance (Lift k, Lift v) => Lift (Map k v)` is now obtained from the `th-lift-instances` library, which is the canonical home for that particular instance.
* The `text` library defines an `instance Lift Text` since version 1.2.4.0. On earlier versions of `text`, an equivalent instance is obtained from the `th-lift-instances` library, which backports it.
> Remove overlapping Lift instance

- .travis.yml
- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent-mongoDB/test/EntityEmbedTestMongo.hs
- persistent-mongoDB/test/main.hs
- persistent-mysql/test/CustomConstraintTest.hs
- persistent-mysql/test/InsertDuplicateUpdate.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/ArrayAggTest.hs
- persistent-postgresql/test/CustomConstraintTest.hs
- persistent-postgresql/test/EquivalentTypeTestPostgres.hs
- persistent-postgresql/test/JSONTest.hs
- persistent-postgresql/test/main.hs
- persistent-qq/test/PersistentTestModels.hs
- persistent-redis/tests/basic-test.hs
- persistent-sqlite/test/main.hs
- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-template/test/main.hs
- persistent-test/persistent-test.cabal
This PR uses StandaloneDeriving to avoid the handwritten instances that currently exist in persistent-template.
In addition, it uses deriving strategies to specify that GeneralizedNewtypeDeriving should be used to derive the instances. This fixes the long-standing issue that derivation would fail if DeriveAnyClass was enabled
* Closes #578
* Closes #738
* Closes #908
I think this is working, but I'd ideally like to test in a larger project to make sure this doesn't massively increase compile times or break any derived instances.
<hr>
> Use StandaloneDeriving and DerivingStrategies in persistent-template

- persistent-sqlite/Database/Persist/Sqlite.hs
In GHC 8.10 (alpha2, at least), a TH splice (eg makeLenses) between
usage and definition of an instance (eg FromJSON) makes the instance
invisible at the usage site, causing an error. Cf
https://gitlab.haskell.org/ghc/ghc/merge_requests/1817#note_242542
This change lets persistent-sqlite build with GHC 8.10-alpha2.
I'm not sure about the other packages (didn't have the right deps
to build mysql).
> persistent-sqlite: a fix for template-haskell 2.16, GHC 8.10 alpha

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
The latest version adds a MonadFail constraint to some functions
I've never used persistent-mongoDB and I'm pretty unfamiliar with it. I also was having trouble installing mongoDB itself to run the tests (admittedly not putting in a ton of effort). However, this change makes the package compile and matches a pattern used elsewhere in the persistent-mongoDB package, so it might be good?
> Compatibility with mongoDB-2.6.0.0

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/CustomConstraintTest.hs
This PR addresses issue #1009 for the PostgreSQL backend. In order to support multiple foreign keys on a single column, we now pass the reference name to `getColumn`, and use it in the where clause when querying foreign keys for the column.
> Fix multiple fk issue with PostgreSQL migrations

- persistent-template/bench/Main.hs
Right now it's not just an uncomment, you also have to replace a , with a [
> Make it easier to uncomment persistent-template benchmarks

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
Add Acquire based interface for starting transactions and getting
connections from a Pool for use in MonadResource instances that are not
MonadUnliftIO, such as Conduit.
> Add Acquire based interfaces for connections.

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-mysql/test/CustomConstraintTest.hs
This is a follow-up PR for issue #1009. We initially fixed it for Postgres, this PR adds the same fix for the MySQL backend.
> Fix multiple fk issue with MySQL migrations

- .travis.yml
- persistent-mysql/test/CustomConstraintTest.hs
- persistent-mysql/test/MyInit.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/CustomConstraintTest.hs
- persistent-postgresql/test/JSONTest.hs
- persistent-postgresql/test/main.hs
- persistent-qq/test/Spec.hs
- persistent-sqlite/test/main.hs
- persistent-template/Database/Persist/TH.hs
- persistent-test/src/Init.hs
- persistent-test/src/MigrationTest.hs
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
- persistent-test/src/TreeTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/persistent.cabal
- persistent/test/main.hs
This PR adds tests for some old issues.
This PR also fixes #373 finally by using the specified tablename in `fixForeignKey`
> Fix foreign key constraints on custom table names

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
Accessing definition across TH splices is an error and 8.10 seems to break on this. See #1033.
> Move Template Haskell splices to end of the file.

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
===
Currently, the `inList` and `ninList` definitions are the same, I think the latter should use the `NotIn` query operator.
> mongodb: Fix `ninList` filter operator

- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/test/main.hs
- persistent-template/Database/Persist/TH.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/ForeignKey.hs
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Types/Base.hs
I tried to fix https://github.com/yesodweb/persistent/issues/910. It works only for table constaints and not for field constraints. Also it only works and is tested on SQLite, but I think making postgres work is just a matter of copy-pase. No existing migrations break.
Some of the options, like 'OnDeleteSetNull' are not useful at the moment, because of the limitation of persistent to only make possible to refer to primary keys of other tables (which can't be NULL anyway).
Not to be confused with what `mkDeleteCascade` does. The approach here is to let the db do all the cascading changes, instead of manually updating other tables. 
> Foreign key cascade

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/main.hs
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-sqlite/test/main.hs
- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-test/persistent-test.cabal
- persistent-test/src/ForeignKey.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
A continuation on #1056 implementing it in Postgresql.
We can't implement this for MySQL until we figure out how to set a `maxlen` on the keys for strings. :\ Well, we could, but we'd need a different set of tests, and I don't feel like writing that out right now. Might as well get sqlite and postgres supported and released.
> Foreign key cascades

- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
> JSON instances require an extraneous id field for entities with a Primary

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
GHC 8.0 and later come with the `DeriveLift` extension for deriving instances of `Language.Haskell.TH.Syntax.Lift`. `persistent-template` supports GHC 8.2 and up, so it is able to make use of this. Not only does `DeriveLift` make for much shorter code, but it also fixes warnings that you get when compiling `persistent-template` with GHC 8.10 or later:
```
[1 of 1] Compiling Database.Persist.TH ( Database/Persist/TH.hs, interpreted )
Database/Persist/TH.hs:267:10: warning: [-Wmissing-methods]
• No explicit implementation for
‘liftTyped’
• In the instance declaration for ‘Lift SqlTypeExp’
|
267 | instance Lift SqlTypeExp where
|          ^^^^^^^^^^^^^^^
Database/Persist/TH.hs:278:10: warning: [-Wmissing-methods]
• No explicit implementation for
‘liftTyped’
• In the instance declaration for …
```
> Use DeriveLift to generate persistent-template's Lift instances

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/ArrayAggTest.hs
- persistent-postgresql/test/CustomConstraintTest.hs
- persistent-postgresql/test/JSONTest.hs
- persistent-postgresql/test/PgInit.hs
- persistent-postgresql/test/PgIntervalTest.hs
- persistent-postgresql/test/main.hs
I wasn't sure how to put all of the db entry keys into scope. I made some ad hoc data structures to do so, but if anyone has any suggestions on how to do this better I would be open to them!
> Note: I used `runIO` instead of `before` or `beforeAll` because I wanted to have access to the db entry keys. Additionally, I didn't insert the `edgeCases` when constructing the spec tree because they mess up some of the earlier tests. I had to insert the `edgeCases` in each `it` block afterwards, so I would still have access to the keys and they wouldn't pollute the db state.
- ~~Bumped the version number~~
- ~~Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)~~
- ~~Added [`@since` …
> Refactor PostgresJSON Tests

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Migration.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/persistent.cabal
Fixes #1079. Running the test script from that issue now prints
Migrating: ALTER TABLE "person" ALTER COLUMN "age" TYPE INT8
[Debug#SQL] ALTER TABLE "person" ALTER COLUMN "age" TYPE INT8; []
persistent-repro-exe:
Database migration: manual intervention required.
The unsafe actions are prefixed by '***' below:
*** ALTER TABLE "person" DROP COLUMN "age";
This is arguably a breaking change, since if people were catching this exception in their code before, they'll need to change their uses of `catch` to catch this type. If #969 was previously released without a breaking-level version bump and nobody complained, though, this is probably okay to release without a breaking-level version bump too?
> Fix display of exception error messages, #1079

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/persistent.cabal
If template haskell is disabled in monad-logger, this needs to
be propagated to persistent. Otherwise, type errors ensue. 
```
Database/Persist/Sql/Raw.hs:43:18: error:
• Couldn't match type ‘Control.Monad.Logger.Loc’
with ‘Language.Haskell.TH.Syntax.Loc’
NB: ‘Language.Haskell.TH.Syntax.Loc’
is defined in ‘Language.Haskell.TH.Syntax’
in package ‘template-haskell-2.14.0.0’
‘Control.Monad.Logger.Loc’
is defined in ‘Control.Monad.Logger’
in package ‘monad-logger-0.3.30’
Expected type: Control.Monad.Logger.Loc
-> Control.Monad.Logger.LogSource
-> Control.Monad.Logger.LogLevel
-> fast-logger-2.4.15:System.Log.FastLogger.LogStr.LogStr
-> IO ()
Actual type: LogFunc
• In the second argument of ‘runLoggingT’, namely
‘(connLogFunc conn)’
In a stmt of a 'do' block:
runLoggingT
(logDebugNS (pack …
```
> Add cabal flag and CPP option to use Loc from monad-logger.

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-redis/ChangeLog.md
- persistent-redis/Database/Persist/Redis/Exception.hs
- persistent-redis/persistent-redis.cabal
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/EmbedTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/Database/Persist/Types/Base.hs
Closes #1107.
~I am not sure about the use of `Typeable` in [persistent-template/Database/Persist/TH.hs](https://github.com/yesodweb/persistent/blob/master/persistent-template/Database/Persist/TH.hs). However, even if it is no longer needed, this may be out of scope for this PR.~ After some research I believe this is handled by Template Haskell, as it should be.
I hope I got the versions/changelogs right.
-----------
> Remove deriving of Typeable.

- persistent-qq/ChangeLog.md
- persistent-qq/persistent-qq.cabal
- persistent-qq/src/Database/Persist/Sql/Raw/QQ.hs
- persistent-qq/test/Spec.hs
> persistent-qq: Add interpolation support for multirow VALUES syntax

- persistent-template/Database/Persist/TH.hs
- persistent/ChangeLog.md
> Don't derive Show for Unique

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/cbits/sqlite3.h
Fixes several longstanding bugs in SQLite and adds a number of new optimisations and features.
More importantly these optimisations will give me super linear speedup for my code ;)
Open question: What should the version bump for `persistent-sqlite` be? Last bump was only a minor one, not sure that should be the case again or not?
> Update SQLite amalgamation to 3.33.0

- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/RawSqlTest.hs
I was non-deterministically getting an error on this test, where the pets were misordered. I'm having trouble reproducing, but I believe the issue is that Postgres' order is non-deterministic if not specified (in my experience, it can be Postgres version dependent). I believe the test as-is is incorrect without specifying the pet order, for Postgres.
[Postgres docs warn:](https://www.postgresql.org/docs/12/queries-order.html)
> After a query has produced an output table (after the select list has been processed) it can optionally be sorted. If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. A particular output ordering can only be …
> Use explicit ordering in RawSqlTest

- persistent-test/src/PersistUniqueTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistUnique.hs
Entities which are already in the DB will conflict with themselves when using `checkUnique`, unless the value of each unique key is changed. This adds an alternative `checkUniqueUpdateable` which ignores conflicts from an entity with itself, so that uniqueness constraints can be checked without an update.
> Add API for checking uniqueness constraints for updates

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-test/src/PersistentTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
**Note**: Since I no longer have access to the previous repository, this replaces PR #1070 . I've applied the suggestions from that PR and I'm updating the changelog files to reflect the new PR number.
This addresses #1069 by adding an `exists` function to the `PersistQueryRead` type class, which already provides the `count` function. The `count` function will be used for a fallback implementation for backends that don't provide a separate existence check.
> Exists query

- .github/workflows/haskell.yml
- cabal.project
- persistent-mysql/test/MyInit.hs
- persistent-postgresql/test/PgInit.hs
- persistent-test/src/Init.hs
This PR implements GitHub Actions as CI as an alternative to Travis.
Alternatively, migrating from `travis-ci.org` to `travis-ci.com` may fix the slowdown issue. But I already got this setup, and it seems like it'll be even nicer. One potential improvement would be a separate CI job for each of the packages, so maintainers can see exactly which database package failed.
Especially if I can get it setup to use the cache from `persistent{,-template}` in `persistent-{mysql,postgres,sqlite}`...
> GitHub Actions CI

- persistent-template/test/main.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Util.hs
> Deprecate hasCompositeKey and provide replacements

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-template/Database/Persist/TH.hs
- persistent-test/src/ForeignKey.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Sql/Internal.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Types/Base.hs
This pr adds some new feautures related to Foreign Keys that are commonly needed:
- allows a reference to a table without an explicit Primary key (fixes #1119 ), 
- allows a reference to non Primary keys, using the keyword `References` (fixes #999, fixes #957 )
- allows simple/field Foreign Keys to have Cascade Options (fixes #1118)
The extended syntax for Foreign Key is like this:
`Foreign <otherTable> [OnDelete...] [OnUpdate...] <fkeyName> list_of_foreign_fields [References list_of_parent_fields]`
It's still a _WIP_ because:
- Some postgres specific implementation is missing (see commit Support Cascade options for SQLite )
- Currently when the `References` keyword is used, there is no check for Unique constraint, so it's the user's responsibility to only refer to unique fields. Should …
> Foreign key improvements

- .github/workflows/haskell.yml
- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
- persistent-template/persistent-template.cabal
- persistent-template/test/SharedPrimaryKeyTest.hs
- persistent-template/test/SharedPrimaryKeyTestImported.hs
- persistent-template/test/main.hs
> Shared Primary Keys

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/test/PgInit.hs
- persistent-postgresql/test/main.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/Database/Persist/Sql/Types.hs
This PR ~is a draft~ shows what it might look like to have a configurable idle timeout and stripe size for Persistent's SQL backends. This would resolve the issues brought up in #775.
~This PR is just a draft~. It's untested and needs a few small additions, but most things are in place. (Edit: added a test)
> Configurable idle timeout

- persistent-postgresql/persistent-postgresql.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
> Add space in cascade SQL and fix docs.

- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
Currently, persistent-test has a bit of version rot. This MR updates the
package's version bounds to be appropriate. Corresponding version bounds
have been pushed to Hackage as revisions.
> Update persistent-test version bounds

- persistent/ChangeLog.md
(I think it's fine to merge this w/o a new release or mentioning it anywhere)
> Fix markdown link syntax in persistent changelog

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-test/src/ForeignKey.hs
I noticed that when the cascade behavior of a field foreign key changes (ie by adding OnDeleteCascade), no migrations is generated. Is there any reason not to? There is a comment `An unspecified 'CascadeAction' is defaulted to 'Restrict' when doing migrations.`, so maybe there is already a way to make migrations work that I missed?
> Fix references Migrations

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/persistent.cabal
- persistent/test/main.hs
Fixes #1175 
---
Currently just a failing test. I should really get this fixed soon.
> [#1175] Empty Entity Parsing

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
Just trying to do a small FIXME here
no haddock changes
> Replace askLogFunc with askLoggerIO

- persistent/ChangeLog.md
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
`withBaseBackend` and `withCompatibleBackend` are simple wrappers for `withReaderT` that use the appropriate read-transforming function from their respective instances.
Also dogfoods these functions into the codebase.
> Add QoL API for using BaseBackend/BackendCompatible

- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Compatible.hs
- persistent/Database/Persist/Compatible/TH.hs
- persistent/Database/Persist/Compatible/Types.hs
- persistent/persistent.cabal
If a backend is compatible with another, it has a lot of obvious instances for various Persistent classes in terms of the backend it is compatible with - `RawSqlite` in the codebase is one example.
This adds a newtype, `Compatible`, which has these compatible instances declared on it. `Compatible` is designed to be used with `DerivingVia` to automatically yield these compatible instances when given a witness of backend compatibility.
To help use `Compatible` and write all the standalone derivations necessary to get a fully-featured compatible backend, this also adds some TH invocations to generate the standalone derivations for a given pair of compatible backend types.
`RawSqlite` is rewritten to dogfood on thes invocations, to prove their effectiveness and simplify the code somewhat. …
> Add newtype, TH functions for deriving instances from backend compat

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/test/main.hs
A refactoring contribution towards https://github.com/yesodweb/persistent/issues/1061
> Refactor [] to NonEmpty in Quasi module

- .github/workflows/haskell.yml
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/PgInit.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
> Backport #1207 to persistent-2.10.5

- .github/workflows/haskell.yml
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/PgInit.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
> Backport the 1207 fix to `persistent-2.11.0`

- persistent/ChangeLog.md
- persistent/persistent.cabal
I accidentally published `persistent-2.12.0.0` -_-
This MR bumps the version.
I've deprecated the 2.12 release as it's not ready to go yet and made it unbuildable on Hackage.
> that's what i get for trusting my zsh prompt

- persistent-template/ChangeLog.md
- persistent-template/Database/Persist/TH.hs
Refactors some variable names in `TH.hs` as a contribution towards https://github.com/yesodweb/persistent/issues/1156
-----
> Renaming values in persistent-template

- persistent/persistent.cabal
`template-haskell-2.17` has some breaking changes, as reported in #1220 
This PR blocks `template-haskell-2.17` in the repo to correspond with the Hackage revision I made.
> Add upper bound on template-haskell

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-redis/ChangeLog.md
- persistent-redis/Database/Persist/Redis/Parser.hs
- persistent-redis/persistent-redis.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
- persistent/test/main.hs
> Fix ToJSON for PersistValue

- .editorconfig
- .github/PULL_REQUEST_TEMPLATE.md
- .stylish-haskell.yaml
- README.md
- development.md
> Add Editor Tooling Files

- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/persistent.cabal
> persistent-2.12.1.0

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
---
Refactors the `TH` module, specifically themed around generating `TH` `Name`s, or `Exp` values that use those names. 
Now I think this module is a lot dry'er, where we have some duplication currently scattered around this module dealing with how names are generated.
For example, the Entity name when using `mpsGeneric` was duplicated in 3 different places, this change has DRY'd this up into a single function.
I considered moving these functions out and into their own module, and adding some HSpec tests for each name generating function, for the key name generating functions at least, such as the constructor name/field accessor names, but thought this might be over kill. I think this functionality is largely covered …
> Refactoring name generating functions in TH

- persistent-postgresql/Database/Persist/Postgresql.hs
This change fixes https://github.com/yesodweb/persistent/issues/1227
> Fixing Haddock formatting for a new method

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/test/main.hs
----
This is a followon from https://github.com/yesodweb/persistent/pull/1206 that addresses the TODO comment here:
https://github.com/yesodweb/persistent/blob/53359c834f649442c2f17379e24d78fb6e8719d4/persistent/Database/Persist/Quasi.hs#L546-L555
Following recent refactoring there is not actually any instance of `Line` where the contents of the list are _not_ `NonEmpty`, so this PR changes that type to always use `NonEmpty`, rather than being polymorphic, which greatly simplifies a lot of the code around `Line`, and means we can also get rid of the `skipEmpty` function, as `NonEmpty` guarantees us nonempty-ness :+1:
> Simplify Line type in Quasi module, always use NonEmpty

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-postgresql/test/PgInit.hs
- persistent-postgresql/test/UpsertWhere.hs
- persistent/Database/Persist/Class/PersistUnique.hs
Postgrseql's `ON CONFLICT DO UPDATE` behavior only allows for a *single* conflicting column. You cannot let it be a catch-all, "on any conflict do update" sort of behavior. 
The initial tests relied on the buggy behavior where a `Primary` was not considered a `Unique` key (see #1090 for more details). Since there was only the one `Primary` key, this behavior went unnoticed. Additionally, the code *only* used the columns for the `Key` of the record - so any other Uniqueness constraints would fail to match.
In app code, the table we wanted to use this on had *two* unique constraints: a custom Unique and an ID columns. This caused a unique key violation error, which we thought this would capture. It did not. So instead, …
> Make upserts handle unique fields (#1233)

- persistent/Database/Persist/TH.hs
> Deprecate mpsGeneric

- persistent/ChangeLog.md
- persistent/test/main.hs
---
Removes the `nonEmptyOrFail` function in favour of making use of `OverloadedLists` after changes in https://github.com/yesodweb/persistent/pull/1231
> Remove nonEmptyOrFail function from recent tests

- persistent-mysql/test/ImplicitUuidSpec.hs
- persistent-postgresql/test/ImplicitUuidSpec.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/DiscoverEntitiesSpec.hs
- persistent/test/Database/Persist/THSpec.hs
- persistent/test/TemplateTestImports.hs
> discoverEntities

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
---
A step towards taming the laddering in the `setEmbedField` function. The main part being consolidating this portion to using `do` notation instead:
https://github.com/yesodweb/persistent/blob/93f688426c35c95e6a70caffe13b76eb9ba98e97/persistent/Database/Persist/TH.hs#L353-L364
I've extracted that out into this top level function here:
```hs
lookupEmbedEntity :: EmbedEntityMap -> FieldDef -> Maybe EntityNameHS
lookupEmbedEntity allEntities field = do
entName <- EntityNameHS <$> stripId (fieldType field)
guard (M.member entName allEntities) -- check entity name exists in embed map
pure entName
```
> Refactor setEmbedField to use do notation

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
---
This PR contains an assortment of various tweaks to the TH module, it inlines some functions, extracts some functions, and contains some general cleanup in the form of whitespace/alignment fixes and stylish-haskell fixes. And is also a bit of a followup on from https://github.com/yesodweb/persistent/pull/1218
> Assorted cleanup of TH module

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
This is for the case where an explicit reference to the opened connection is convenient.
Some of the conditions that make having this helpful are:
1. Being able to control when to call `Database.MySQL.Base.initThread`.
2. Being able to use `mysql-simple` when necessary, but still using `persistent` for model definitions and other advantages, like migrations.
@lehins @f-f @neilmayhew
-----
> Expose `openMySQLConn` for when an explicit reference to the connection may be convenient

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/MultiBlockSpec.hs
- persistent/test/Database/Persist/TH/MultiBlockSpec/Model.hs
- persistent/test/Database/Persist/THSpec.hs
> Check for existence of entities before generating them

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/TH.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/test/Database/Persist/TH/KindEntitiesSpec.hs
- persistent/test/Database/Persist/TH/KindEntitiesSpecImports.hs
- persistent/test/Database/Persist/THSpec.hs
- persistent/test/main.hs
--------
Closes https://github.com/yesodweb/persistent/issues/1166
I've opened this as a draft PR with a view towards getting some feedback on it still. I think everything here should be fine for addressing that ticket, but there might be something I have overlooked here. I will annotate what I've got so far.
I have also opened this PR against `master` as it is not a super invasive change, and I would be happy to deal with porting it forward into the `persistent-2.13` branch after it is merged in. Alternatively if it is preferred that this PR goes against that branch, and is backported to `master`, I'd be happy to do that as well.
It may also make sense for this to just go into `2.13` like my other recent change :+1:
> Support promoted types in Quasi Quoter

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/PersistWith/Model.hs
- persistent/test/Database/Persist/TH/PersistWith/Model2.hs
- persistent/test/Database/Persist/TH/PersistWithSpec.hs
- persistent/test/Database/Persist/TH/SharedPrimaryKeyImportedSpec.hs
- persistent/test/Database/Persist/THSpec.hs
> Fix duplicate entity checks

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Migration.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/persistent.cabal
The Haddocks around CautiousMigration were ambiguous, since it wasn't clear if the flag signified whether each migration was safe or not - and there is at least one instance in the code that gets it wrong.
This corrects that error, opting to make the `addMigration` documentation match the code's behaviour.
Personally, I think the better approach to this mess would be to replace all the use of `(Bool, Text)` with a datatype that enforces better usage through a stricter API - something like
```haskell
data CautiousSql = MkCautiousSql { ... } -- Hide this constructor
-- Expose these smart constructors
mkSafeSql :: Sql -> CautiousSql
mkSafeSql = ...
mkUnsafeSql :: Sql -> CautiousSql
mkUnsafeSql = ...
-- Expose these instead of record fields
isUnsafe :: CautiousSql -> Bool
isUnsafe = ... …
```
> Improve documentation around migration safety

- persistent-mongoDB/test/main.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/main.hs
- persistent-sqlite/test/main.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/MaybeFieldDefsTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/FieldDef.hs
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/Sql/Class.hs
- persistent/Database/Persist/Sql/Internal.hs
- persistent/Database/Persist/TH.hs
- persistent/Database/Persist/Types.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/MaybeFieldDefsSpec.hs
- persistent/test/Database/Persist/THSpec.hs
Closes https://github.com/yesodweb/persistent/issues/277
> Support declaring Maybe before the type in model definitions

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/CommentSpec.hs
- persistent/test/Database/Persist/THSpec.hs
- persistent/test/test/Database/Persist/THSpec.hs
> Fix order of field comments

- persistent/ChangeLog.md
- persistent/Database/Persist.hs
- persistent/Database/Persist/Class.hs
- persistent/Database/Persist/Class/PersistQuery.hs
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Migration.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/Database/Persist/Types.hs
- persistent/persistent.cabal
#1308 made it pretty clear that our docs are not visible or accessible, especially for the `Quasi` module. This PR reorganizes documentation and module stuff, along with providing more docs in a few areas.
> Big Documentation Reorganization

- persistent/ChangeLog.md
- persistent/Database/Persist.hs
- persistent/Database/Persist/Quasi.hs
Fixes a couple of typos and Haddock rendering issues.
> Fix typos and rendering issues in docs

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
This is useful with things like castNum.
Didn't do these, since I'm not sure which ones are applicable:
> Add a Num instance for OverflowNatural

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/persistent.cabal
This is part of the followup to #1298.
This exposes `orderClause` in a similar manner to `filterClause`, to help third-party libraries which want to format their own SQL queries using Persistent's internal helpers.
It rewrites `orderClause` a bit to bring it in line with the other exposed functions, but there should be no functional changes as a result.
> Expose orderClause from PersistQuery.hs

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/Database/Persist/Postgresql/Internal.hs
- persistent-postgresql/persistent-postgresql.cabal
This is part of the followup to #1298.
The code exposed in this new `Database.Persist.Postgresql.Internal` module is very helpful to third-party libraries which want to use functions from `postgresql-simple` to produce `PersistValue`s for feeding to `persistent` functions.
Exposing them is necessary to allow for a third-party library which provides streaming of Persistent entities using Postgres cursors.
> Expose PSQL parser helpers in new 'Internal' module

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
The big idea here is that if a user or something besides `Database.Persist.TH` writes a `C a => PersistEntity (Foo a)` instance, we don't want `discoverEntities` to find it and include a `entityDef (Proxy :: Proxy (Foo a))` in the list, because there's no way that's going to work (unless `C` is a trivial typeclass).
---
markup](https://www.haskell.org/haddock/doc/html/index.html)~
declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since)
to the Haddock~
> Don't discover constrained instances

- persistent-postgresql/test/JSONTest.hs
- persistent-postgresql/test/PgInit.hs
- persistent-postgresql/test/main.hs
- persistent-qq/test/PersistentTestModels.hs
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-test/src/Init.hs
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/Database/Persist/Class/PersistConfig.hs
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/PersistValue.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/JsonEncodingSpec.hs
- persistent/test/Database/Persist/THSpec.hs
- stack.yaml
Issue: #1344
Cherry-picks from https://github.com/yesodweb/persistent/pull/1335 and https://github.com/yesodweb/persistent/pull/1338
seems like GHC 9.2 support for dependencies could take a while, so I would appreciate an earlier release with only aeson 2 support.
The Arbitrary Value instance in the pg tests was more restrictive than the one in aeson 2.0.3.0 so i newtyped it.
> aeson 2.0 support (only)

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
Similar to like we have `BackendCompatible SqlBackend SqlBackend`. I had to add this one as an orphan in a project using `persistent-postgresql-streaming`, so thought it might be useful here.
> Add `BackendCompatible (RawPostgresql b) (RawPostgresql b)` instance.

- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-mysql/test/JSONTest.hs
- persistent-mysql/test/main.hs
- stack-8.10.yaml
- stack-8.10.yaml.lock
- stack.yaml
- stack_lts-12.yaml
Now that mysql-simple and mysql have been updated to properly handle JSON values coming out of a mysql db (supported since mysql 5.7.8) this PR adds support to the MySQL backend to read these values. It does not add a PersistField instance for Value's. It is probably not great that Postgres has an orphan instance for Value. Would rather there be a Json newtype and JsonB newtype. 
> Add mysql json field support

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent-test/persistent-test.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Raw.hs
- persistent/Database/Persist/Sql/Run.hs
- persistent/Database/Persist/Sql/Types.hs
- persistent/Database/Persist/Sql/Types/Internal.hs
- persistent/Database/Persist/SqlBackend.hs
- persistent/Database/Persist/SqlBackend/Internal.hs
- persistent/Database/Persist/SqlBackend/Internal/MkSqlBackend.hs
- persistent/Database/Persist/SqlBackend/Internal/SqlPoolHooks.hs
- persistent/Database/Persist/SqlBackend/Internal/StatementCache.hs
- persistent/Database/Persist/SqlBackend/SqlPoolHooks.hs
- persistent/Database/Persist/SqlBackend/StatementCache.hs
- persistent/persistent.cabal
This PR builds on top of https://github.com/yesodweb/persistent/pull/1327
It adds support for hooking into various aspects of the lifecycle of a connection / statements. This functionality opens up support for tracing queries within the context of a larger chunk of code: 
To see how this is being used, see the hs-opentelemetry project: https://github.com/iand675/hs-opentelemetry/blob/main/instrumentation/persistent/src/OpenTelemetry/Instrumentation/Persistent.hs
> Add SQL Connection & Statement hooks

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
Fixes #1358.  I believe this remains compatible with older versions of MySQL, so should be a minor version bump.
> Fix anomalies in migration of integer columns in MySQL 8 (#1358)

- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent-test/src/MigrationIdempotencyTest.hs
The extra fields in the migration idempotency test are intended to show the problem in #1358, and test the fix which will come separately.  Before that fix is applied, the test is *expected to fail* when run against MySQL 8.
I have kept this PR separate from the fix since it is run for other backends too, making it somewhat independent.
> Further integer types in migration idempotency test

- .github/workflows/haskell.yml
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent-mongoDB/test/EntityEmbedTestMongo.hs
- persistent-mongoDB/test/main.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/main.hs
- persistent-redis/persistent-redis.cabal
- persistent-test/src/DataTypeTest.hs
- persistent/Database/Persist/Class/PersistField.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
This is based on #1338 but avoids overriding dependencies. The compatible targets are built and tested in CI, ~~the others are marked as unbuildable and cabal-install will just skip them.~~ EDIT: nothing is disabled any more
> Allow GHC 9.2 for compatible packages

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/test/Database/Persist/QuasiSpec.hs
-----
A further contribution towards https://github.com/yesodweb/persistent/issues/1156, addresses the fold referenced in that issue by creating a type that holds the various possible constraints, and can be built up and merged into one. I have used `Monoid`s / `Semigroup`s however the instances are not lawful. I will put some further detail about this as a comment in the relevant area in the PR.
I have also renamed `splitExtras` to `parseEntityFields` as this is more descriptive I think. This function is called when the fields of an entity are extracted, the first step being to split the `'extra'` tokens from the rest of the entity fields which are added to a value of type `M.Map Text [ExtraLine]`, where the key is …
> Refactor entity constraint parsing in Quasi module

- persistent/Database/Persist/Sql/Run.hs
> Add missing apostrophe to acquireSqlConn docs

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/THSpec.hs
> Fix JSON import

- persistent/ChangeLog.md
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/RequireOnlyPersistImportSpec.hs
- persistent/test/Database/Persist/THSpec.hs
Follow on from https://github.com/yesodweb/persistent/pull/1369. Though that PR adds some additional coverage to preventing this from happening again, this PR adds an additional spec to explicitly verify we can generate entities where `Data.Persistent.TH` is the only import required.
---
> Add spec to assert Persistent.TH is the only import required when defining entities

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-mysql/test/main.hs
Fixes #1373. **This PR has now been modified to include the fix**
Fixes the bug, and adds a test - an existing one, but it wasn't run for MySQL.
It **fails at present,** but that is the point!  There will be a separate issue in a minute.
> Fix adding new column in persistent-mysql, and include MigrationTest

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/test/Database/Persist/QuasiSpec.hs
Ups the test coverage in `QuasiSpec` to cover cases when there is an error, and make an assertion on the error message. 
The original motivation for this was discovering that this error here:
https://github.com/yesodweb/persistent/blob/aeaa4f61159e140fbf3a45fc2b59309b0bb4b53f/persistent/Database/Persist/Quasi/Internal.hs#L1155-L1157
Is actually `show`ing all the `UnboundField`s as illustrated in this commit prior to fixing:
https://github.com/yesodweb/persistent/pull/1374/commits/89b34a9b5e468b18b030591843c380a9ee60bb20#diff-31a6cff4e15cd1978c97554cd4fae33101b142ab0e6a6e03f427458d2851b26bR457
This PR corrects this, and extracts a function to generate the error message in a more type safe way.
Further to this I have added some similar tests around other errors in this module which do not …
> Increasing test coverage for errors thrown when parsing entity definitions

- persistent-mongoDB/test/main.hs
- persistent-mysql/test/main.hs
- persistent-postgresql/test/PgInit.hs
- persistent-postgresql/test/main.hs
- persistent-sqlite/test/main.hs
- persistent-test/persistent-test.cabal
- persistent-test/src/TypeLitFieldDefsTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/TH.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/QuasiSpec.hs
- persistent/test/Database/Persist/TH/TypeLitFieldDefsSpec.hs
- persistent/test/Database/Persist/THSpec.hs
Continuation of #1343
Fixes #562 
> Finalize type lits

- persistent/ChangeLog.md
- persistent/test/Database/Persist/QuasiSpec.hs
> Increasing quasi module test coverage, improve error assertions

- docs/README.md
The documentation for `.persistentmodels` files is here, in `Database.Persist.Quasi`: https://hackage.haskell.org/package/persistent-2.14.0.0/docs/Database-Persist-Quasi.html, but it's very hard to find:
- A Google search for "persistentmodels syntax" links to https://hackage.haskell.org/package/persistent-parser-0.1.0.2/docs/Database-Persist-Syntax-Types.html
- Which links to https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax (I've since updated this page with a direct link to the documentation) 
- Which links to https://github.com/yesodweb/persistent/tree/master/docs#wiki
- Which links to https://github.com/yesodweb/persistent/blob/master/docs/Persistent-entity-syntax.md
- Which links to the actual documentation
This PR makes the …
> Update "Entity Syntax" link to go directly to Database.Persist.Quasi

- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/persistent.cabal
> Remove `HasField` and pattern synonym

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/NoFieldSelectorsSpec.hs
- persistent/test/Database/Persist/TH/OverloadedLabelSpec.hs
- stack.yaml
This PR fixes #1406 which noticed that the code generated name shadowing warnings.
The specific problem si that we'd generate code like:
```haskell
case someRecord of
Constructor { fieldName = fieldName } -> ...
```
where `fieldName` shadowed `fieldName`.
> Fix a name shadowing warning (#1406)

- persistent/ChangeLog.md
- persistent/Database/Persist/Names.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/persistent.cabal
> Fix typo: FieldNameDB calls itself EntityNameDB

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
I have literally no idea why haddock was unhappy about them before, but I just changed it to a block comment and it worked.
Haddock wasn't seeing them at all, to be clear: it thought there were no docs. No idea what that was about.
> Fix docs for discoverEntities being jacked

- persistent/Database/Persist/Types/Base.hs
Typo fix.
I guess `FieldAttrNoreference` is an alternative answer to https://github.com/yesodweb/persistent/issues/1377
cc @erikd
> Fix typo in FieldAttrNoreference comment

- persistent/Database/Persist/TH.hs
Just suggesting a wording change on the warning message when trying to add a uniqueness constraint to a nullable column.
Some people were confused about whether this warning came from our in-house code or from Persistent, so I clarified that. Also, some people were confused about whose equality semantics treated nulls as not equal, so I clarified that it's a SQL thing.
~~~
> Clarify error message wording

- docs/README.md
- persistent-mongoDB/test/EmbedTestMongo.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/PersistWith/Model.hs
- persistent/test/Database/Persist/TH/PersistWithSpec.hs
Fixes #1445 
Fixes #1439 
The QQ is only capable of resolving keys of the form `FooId`. It can't work with qualified types, or the `Key`, and fails with `(Maybe FooId)`, too.
> Improve foreign key discovery

- persistent/ChangeLog.md
- persistent/Database/Persist/PersistValue.hs
- persistent/persistent.cabal
Fully evaluating a `PersistValue` is important for gathering correct metrics. E.g. to get an accurate estimation of how long the SQL itself takes to run, it's essential to force the `[PersistValue]` which is used to construct the statement _before_ starting the timer.
> NFData PersistValue

- cabal.project
- persistent-redis/persistent-redis.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Run.hs
- persistent/persistent.cabal
- stack.yaml
Tested locally by forcing `mtl == 2.3.1` in the `constraints`. Appears to work OK.
`persistent-redis` has an upper bound, but `hedis` itself can't work. Pending https://github.com/informatikr/hedis/pull/190 PR. 
> Support `mtl >= 2.3`

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Orphan/PersistStore.hs
- persistent/persistent.cabal
`repsertMany` admits backends to provide a custom implementation via `connRepsertManySql`. in the case of the postrgres backend, repsertMany becomes an atomic operation.  It would be nice to take advantage of this for `repsert` as well.  (it's fairly well known as a gotcha in our codebase but this would be a nice QoL improvement for us)
> make repsert a special case of repsertMany

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/NoFieldSelectorsSpec.hs
There was a couple of places where it still generates code using selector functions; this PR replaces them with `fieldSel`.
> fix a problem preventing use of Primary with NoFieldselectors

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
When reading `migrate'` implementations of `persistent-sqlite` and `persistent-postgresql` it took me a while to figure out what `(Bool, Text)` actually means. Using the type alias from `Database.Persist.Sql.Migration` makes it clearer.
> Make use of `CautiousMigration` type alias in SQL backends.

- persistent/ChangeLog.md
- persistent/Database/Persist/Sql/Util.hs
The list produced by `toPersistFields entity` is already of type `[PersistValue]`. This can be checked by putting a type hole inside, which will reveal that `toPersistValue` call in this context has `PersistValue -> PersistValue` type and boils down to `id`.
> Remove extraneous `map toPersistValue` call.

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
I needed to make this change to have this module compile with GHC-9.6.1-alpha1.
I see that there is already an mtl-2.3 compat branch merged, so I'm not sure why this wasn't picked up there.
Perhaps this was being re-exported by something else?
> Explicitly import Control.Monad.Trans for mtl-2.3 compat

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/NoFieldSelectorsSpec.hs
To avoid the problem that GHC fails compiling due to parse error when the field name generated by Template Haskell matches any of Haskell keywords, this PR fixes `mkRecordName` to suffix `_` if the field name matches any of keywords.
> Avoid parse error occurred when the field name generated by TH matches any of Haskell keywords

- persistent-test/src/ReadWriteTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
> Add insertUnique_ to PersistUniqueWrite

- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-test/src/PersistUniqueTest.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistUnique.hs
- persistent/Database/Persist/Compatible/Types.hs
- persistent/Database/Persist/Sql/Orphan/PersistQuery.hs
- persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
- persistent/Database/Persist/Sql/Util.hs
- persistent/persistent.cabal
This adds `existsBy` in `PersistUniqueRead`, as a more efficient version of `isJust <$> getBy uniq`.
The intent is to provide an (a) more convenient to type and (b) more efficient way to query existence of a row by unique key.
The SQL is a combination of the `exists` and `getBy` impls, and looks like `SELECT EXISTS (SELECT 1 FROM ...constraints...)`.
The performance difference shouldn't be large, but conceivably on wider tables (or with heavy columns eg. JSON or binary blobs), `existsBy` would require less serialization (just a single response column) and may allow the query planner to do an index-only plan.
What do you think?
---
> Add existsBy

- persistent-qq/test/Spec.hs
mtl-2.3 removes these reexports
> Import `Control.Monad` in `persistent-qq`

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/test/Database/Persist/TH/CompositeKeyStyleSpec.hs
With a persistent definition like,
```
Customer
firstName String
lastName String
Primary firstName lastName
```
the `keyFromRecordM` was generated like 
```
keyFromRecordM = Just
(\ Customer {customerFirstName = customerFirstName,
customerLastName = customerLastName}
-> (CustomerKey customerFirstName) customerLastName)
```
hence the name-shadowing error.
The fixes is simply append index to those variables, like
```
keyFromRecordM
= Just
(\ Customer {customerFirstName = customerFirstName_1,
customerLastName = customerLastName_2}
-> (CustomerKey customerFirstName_1) customerLastName_2)
```
-----
> Fixes name shadowing error at keyFromRecordM for Primary keys

- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
Written by referring, in part, to:
* the description in the Cabal file for [`attoparsec-aeson-2.1.0.0`](https://hackage.haskell.org/package/attoparsec-aeson-2.1.0.0); and
* the migration guide in the change log of [`th-abstraction-0.6.0.0`](https://hackage.haskell.org/package/th-abstraction-0.6.0.0/changelog).
Tested by building Stack (which depends on `persistent`) using GHC 9.8.0.20230809 on Alpine Linux (on WSL 2) and a dependency on `aeson-2.2.0.0`.
> Fix #1512 Allow use with aeson >= 2.2.0.0 and GHC 9.8

- persistent/ChangeLog.md
- persistent/Database/Persist/Quasi.hs
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/TH/CommentSpec.hs
- persistent/test/Database/Persist/TH/EntityHaddockSpec.hs
- persistent/test/Database/Persist/THSpec.hs
This PR adds a flag to `MkPersistSettings` which enables Haddock generation from entity documentation comments. The default is `False` to avoid any unexpected performance impacts from upgrading `persistent`.
Fixes #1462.
---
- Changes to the documentation assume that this feature will be made available in `persistent` version `2.14.6.0`.
- `stylish-haskell` fails on the `#if`-`#else`-`#endif` construct in the import list in `TH.hs` as all three preprocessor directives are ignored, resulting in two identifier lists for `Language.Haskell.TH.Lib`.
> Create Haddocks from entity documentation comments

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/Database/Persist/Postgresql.hs
- persistent-postgresql/persistent-postgresql.cabal
This change adds a connection pool creation function that is just like the `createPostgresqlPoolModifiedWithVersion` function but that can take a custom `open'`-like connection-creation function.
The motivation for this change is that we need to be able to customize the resource creation action dynamically at run-time.
> persistent-postgresql: add `createPostgresqlPoolTailored` function

- persistent-postgresql/ChangeLog.md
- persistent-postgresql/persistent-postgresql.cabal
> Bump versions for postgresql-simple and postgresql-libpq

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/test/Database/Persist/TH/OverloadedLabelSpec.hs
- Regardless the type of primary key, there is always a `{EntityName}Id` type hence I think it's safe to always create a `SymbolToField` instance for ID.
> Always creates `SymbolToField "id"` instance

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
This adds a new function for manually constructing a `RawSqlite SqlBackend` connection without having to use the resource-cleaning `with*` functions.
I want to use this because I'm working with a `resource-pool` fork and I don't want to be constricted by the API exposed by `persistent-sqlite` for creating pools - but I can't create my own custom pool without a way to create new `RawSqlite SqlBackend` resources from scratch that don't get automatically cleaned up.
---
> persistent-sqlite: Add `openRawSqliteConn`

- persistent/Database/Persist/Types/Base.hs
This PR adds a version of the `keyAndEntityFields` function which includes `MigrationOnly` and `SafeToRemove` fields. We would like to make use of this in `persistent-documentation` in order to generate documentation for fields marked by those modifiers.
> Add keyAndEntityFieldsDatabase function to return key with migration only fields

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
This PR adds an option in `MkPersistSettings` to customise function for field accessors applied only when the field name matches any of Haskell keywords. (inspired by @parsonsmatt 's comment in https://github.com/yesodweb/persistent/pull/1476#pullrequestreview-1322377621)
> Add `mpsAvoidHsKeyword` in `MkPersistSettings`

- persistent-redis/persistent-redis.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/test/Database/Persist/THSpec.hs
When a table name is specified with qualifier, the guessed name for SqlType had better be qualified by default in order to avoid   potential name collisions with the unqualified name.
> Handle qualified table name

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
This allows using a sqlite database that is in a directory whose name cannot be expressed using Text.
Fixes https://github.com/yesodweb/persistent/issues/1481
Eventually it would make sense for open to use OsPath, but the [Abstract FilePath Proposal](https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/abstract-file-path) is still rolling out. In the meantime, this avoids an API change for users of open.
> add Database.Sqlite.open' which takes a ByteString

- persistent-mysql/ChangeLog.md
- persistent-mysql/Database/Persist/MySQL.hs
- persistent-mysql/test/MyInit.hs
- persistent-mysql/test/main.hs
I noticed that our application reports schema mismatch after upgrading to MySQL 8.0, even if I change the column type to `SqlOther "tinyint"` (removing the width). I realised that the recent versions of persistent-mysql parses tinyint as SqlBool, but it doesn't work in our usecase, where some tinyint columns represent non-Boolean values.
After this change, I confirmed that our application works both on MySQL 5.7 and MySQL 8.0, but I'm not quite confident that this change is in the right direction. What are your thoughts?
----
> persistent-mysql: treat tinyint as SqlOther "tinyint", not SqlBool

- .github/workflows/haskell.yml
- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/cbits/sqlite3.h
- persistent-sqlite/persistent-sqlite.cabal
> Upgrade Sqlite Amalgamation

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Persist/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
> Add Database.Persist.Sqlite.createSqlitePoolWithConfig

- cabal.project
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/persistent.cabal
- stack.yaml
This issue addresses #1527 
If the `denominator` is `1`, then we allow it. Otherwise, we go boom.
This *should* fix the issue with `esqueleto`.
> Allow `Integral` types to parse `PersistRational`

- persistent/Database/Persist/Quasi.hs
Add docs to the quasiquoter module about how the `!no-migrate` entity attribute will prevent any migrations from being generated for an entity. This is currently only "documented" in the source code:
https://github.com/yesodweb/persistent/blob/97013604d9ca9bf39b03a36005287027b621bfff/persistent/Database/Persist/TH.hs#L2769
This has existed for a while, does it need a `@since` declaration or CHANGELOG entry in here?
> Document the `!no-migrate` Entity Attribute

- cabal.project
A new version of postgresql-simple has been released.
Nothing needs to be changed on Hackage as `cabal.project` does not end up on Hackage.
> cabal.project: Remove redundant allow-newer stanzas

- persistent/ChangeLog.md
- persistent/Database/Persist/TH.hs
- persistent/persistent.cabal
> Fix type error message with AtLeastOneUniqueKey class

- persistent-mongoDB/ChangeLog.md
- persistent-mongoDB/Database/Persist/MongoDB.hs
- persistent-mongoDB/persistent-mongoDB.cabal
Replace mongo driver `save` and `replace` API calls with `updateMany` to restore correct behavior in MongoDB >=6.0
This is an extension of https://github.com/yesodweb/persistent/pull/1545. The change in behavior lies in the underlying driver `update` function which  is called indirectly via persistent's `repsert` and `replace` APIs. In this function, the driver uses a write concern of 0 overriding the preference set by the mongo access mode or default write concern as configured in the DB. In test suites or other scenarios where the written data is immediately queried for again from a secondary this can result in flaky "Not Found" failures.
I have opened a [PR](https://github.com/mongodb-haskell/mongodb/pull/156) against the driver library to directly address this issue among others, …
> Update mongo repsert and replace calls

- .envrc
- .gitignore
- cabal.project
- flake.lock
- flake.nix
- persistent-mongoDB/persistent-mongoDB.cabal
- persistent-mysql/persistent-mysql.cabal
- persistent-postgresql/persistent-postgresql.cabal
- persistent-sqlite/persistent-sqlite.cabal
- persistent-template/persistent-template.cabal
- persistent-test/persistent-test.cabal
- persistent/persistent.cabal
The Nix Flakes environment was not buildable at all,
so I fixed it to be functional.
Since it was not buildable at all,
I rewrote it to use haskell.nix,
which can automatically analogize rules from cabal files.
If Nix can build databases and other environments in one shot,
it should be useful for developing persistent with a lot of external tools and complexity.
In fact, I am going to try a bit of persistent and wasm collaboration in the future,
but without the nix environment,
I had a hard time working with a smooth reproducible build,
so I regenerated the flake.nix environment first.
---
This pull request includes various changes to configuration files to improve the setup and dependencies for the Haskell project. The most important changes include updates to the `flake.nix` …
> chore: fix `flake.nix` workable

- persistent/ChangeLog.md
- persistent/Database/Persist/TH/Internal.hs
I found the documentation for `mpsFieldLabelModifier` harder to understand than necessary. So let's fix it. A PR for `mpsConstraintLabelModifier` might follow.
> Document mpsFieldLabelModifier with example

- persistent-test/persistent-test.cabal
- persistent-test/src/PersistentTest.hs
- persistent-test/src/PersistentTestModels.hs
- persistent/ChangeLog.md
- persistent/Database/Persist/EntityDef.hs
- persistent/Database/Persist/Quasi/Internal.hs
- persistent/Database/Persist/Quasi/Internal/ModelParser.hs
- persistent/Database/Persist/TH/Internal.hs
- persistent/Database/Persist/Types.hs
- persistent/Database/Persist/Types/Base.hs
- persistent/Database/Persist/Types/SourceSpan.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/QuasiSpec.hs
- persistent/test/Database/Persist/THSpec.hs
This PR uses Megaparsec to reimplement the tokenization and initial parsing of entity definitions.
**It also slightly changes the semantics of documentation comments**; it is now possible to write Haddock-style pre-comment blocks:
```
-- | This is a multi-line documentation block 
-- in the style of Haddock pre-comments.
-- | This is a multi-line documentation block
-- | in the old Persistent style, which is still
-- | supported.
```
Other than this, there are no intentional changes in behavior. Before merging this, I think it would be a very good idea to test that some other packages depending on persistent (e.g. Esqueleto) build and run correctly with these changes. **I have not done this yet**, but I think I should open the PR anyway so I can get feedback.
---
Before submitting your …
> use Megaparsec for first-pass parsing of entity definitions

- persistent-sqlite/ChangeLog.md
- persistent-sqlite/Database/Sqlite.hs
- persistent-sqlite/persistent-sqlite.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistField.hs
- persistent/persistent.cabal
- persistent/test/Database/Persist/ClassSpec.hs
I noticed that the Sqlite formatting from UTCTime values to string (sqlite doesn't support datetime natively) is missing the UTC timezone marker "Z". So it should be e.g. "2025-04-12T06:53:42Z" instead of "2025-04-12T06:53:42".
I made this change is non-breaking (UTC timezone was implicitly assumed before) by keeping the old parsing logic so new and old format can be read from existing databases.
Loosely related to #1542 #1117 and #339 
> Fix missing UTC timezone "Z" in Sqlite UTCTime strings

- persistent-postgresql/Database/Persist/Postgresql.hs
Expand the documentation of the Postgres version of `upsertManyWhere`: it wasn't clear how the second argument behaves and at least two coders interpreted it backwards introducing a subtle production bug; hopefully the examples now make it clear!
I don't have a dev env setup for this so I didn't run `stylish-haskell`, nor do I know if a documentation update warrants a version bump — happy to comply if necessary though!
> Elaborate on 'upsertManyWhere'

- persistent-qq/src/Database/Persist/Sql/Raw/QQ.hs
I think n/a on all of the above
Not sure if this warrants a changelog entry
> Fix errant references to Database.Persist.Sql.Raw

- persistent-test/ChangeLog.md
- persistent-test/persistent-test.cabal
- persistent/ChangeLog.md
- persistent/Database/Persist/Class/PersistEntity.hs
- persistent/Database/Persist/TH/Internal.hs
- persistent/persistent.cabal
> Add tabulateEntityApply
